#!/usr/bin/env node
/**
 * Outputs puzzles.js content from verified grids.
 * Strategy: Use simple patterns where every intersection is verified.
 */

const clueBank = {
  // 2 letters
  "GO": "Proceed",
  "NO": "Negative response",
  "ON": "Switched ___; active",
  "TO": "In the direction of",
  "DO": "Perform an action",
  "SO": "Therefore; thus",
  "UP": "Toward the sky",
  "IN": "Inside; within",
  "AT": "Preposition of location",
  "AN": "Article before a vowel",
  "AS": "Similar to; like",
  "BE": "Exist; live",
  "IT": "Pronoun for a thing",
  "OR": "Alternative conjunction",
  "IF": "Conditional word",
  "AM": "Morning hours (abbr.)",
  "IS": "Verb of being",
  "ME": "First-person pronoun",
  "HE": "Male pronoun",
  "WE": "Plural first person",
  "RE": "Concerning; about",
  // 3 letters
  "ACE": "Top card; expert pilot",
  "ACT": "Perform on stage",
  "ADD": "Sum up numbers",
  "AGE": "How old someone is",
  "AID": "Help; assistance",
  "AIM": "Point at a target",
  "AIR": "What we breathe",
  "ALE": "Pub brew",
  "ANT": "Colony insect",
  "APE": "Gorilla or chimp",
  "ARC": "Curved line",
  "ARE": "Plural of 'is'",
  "ARK": "Noah's boat",
  "ARM": "Body limb",
  "ART": "Painting or sculpture",
  "ATE": "Consumed food",
  "AWE": "Wonder and amazement",
  "AXE": "Chopping tool",
  "BAD": "Not good",
  "BAG": "Carrying sack",
  "BAN": "Prohibit",
  "BAR": "Pub counter",
  "BAT": "Baseball stick",
  "BED": "Sleeping furniture",
  "BET": "Wager; gamble",
  "BIG": "Large in size",
  "BIT": "Small piece",
  "BOW": "Ribbon knot",
  "BOX": "Cardboard container",
  "BUS": "Public transport vehicle",
  "BUT": "However; except",
  "BUY": "Purchase",
  "CAB": "Taxi vehicle",
  "CAN": "Tin container",
  "CAP": "Head covering",
  "CAR": "Automobile",
  "CAT": "Feline pet",
  "CUB": "Young bear",
  "CUP": "Drinking vessel",
  "CUT": "Slice with scissors",
  "DAD": "Father, informally",
  "DAM": "River barrier",
  "DAY": "24-hour period",
  "DEN": "Animal's lair",
  "DEW": "Morning moisture",
  "DID": "Past tense of 'do'",
  "DIG": "Excavate earth",
  "DIM": "Not bright",
  "DIP": "Submerge briefly",
  "DOC": "Doctor, informally",
  "DOE": "Female deer",
  "DOG": "Man's best friend",
  "DOT": "Small round mark",
  "DRY": "Not wet",
  "DUE": "Owed; expected",
  "DUG": "Past tense of 'dig'",
  "EAR": "Hearing organ",
  "EAT": "Consume food",
  "EEL": "Snake-like fish",
  "EGG": "Oval breakfast item",
  "ELF": "Santa's helper",
  "ELM": "Shade tree",
  "END": "Finish; conclusion",
  "ERA": "Historical period",
  "ERR": "Make a mistake",
  "EVE": "Night before",
  "EWE": "Female sheep",
  "EYE": "Sight organ",
  "FAN": "Cooling device",
  "FAR": "Not close",
  "FAT": "Plump; overweight",
  "FED": "Given food",
  "FEW": "Not many",
  "FIG": "Fruit for a Newton",
  "FIN": "Fish appendage",
  "FIT": "In good shape",
  "FLY": "Buzzing insect",
  "FOG": "Thick mist",
  "FOR": "In favor of",
  "FOX": "Clever canine",
  "FUN": "Enjoyment",
  "FUR": "Animal coat",
  "GAP": "Opening; space",
  "GAS": "Fuel for cars",
  "GEM": "Precious stone",
  "GET": "Obtain; receive",
  "GOD": "Supreme being",
  "GOT": "Obtained; received",
  "GUM": "Chewing candy",
  "GUN": "Firearm",
  "GUT": "Stomach; instinct",
  "GYM": "Exercise facility",
  "HAD": "Possessed; owned",
  "HAM": "Cured pork",
  "HAS": "Possesses",
  "HAT": "Head covering",
  "HEN": "Female chicken",
  "HER": "Female pronoun",
  "HID": "Concealed",
  "HIM": "Male object pronoun",
  "HIS": "Male possessive",
  "HIT": "Strike forcefully",
  "HOG": "Large pig",
  "HOT": "Very warm",
  "HOW": "In what manner",
  "HUG": "Embrace warmly",
  "ICE": "Frozen water",
  "ILL": "Sick; unwell",
  "INN": "Small hotel",
  "IRE": "Anger; wrath",
  "IRK": "Annoy; bother",
  "IVY": "Climbing plant",
  "JAB": "Quick punch",
  "JAM": "Fruit spread",
  "JAR": "Glass container",
  "JAW": "Mouth bone",
  "JET": "Fast aircraft",
  "JOB": "Employment",
  "JOG": "Slow run",
  "JOT": "Write quickly",
  "JOY": "Great happiness",
  "JUG": "Pouring pitcher",
  "KEY": "Door opener",
  "KID": "Young child",
  "KIT": "Set of tools",
  "LAP": "One circuit",
  "LAW": "Legal rule",
  "LAY": "Put down flat",
  "LED": "Guided; conducted",
  "LEG": "Walking limb",
  "LET": "Allow; permit",
  "LID": "Container cover",
  "LIE": "Untruth; recline",
  "LIP": "Mouth edge",
  "LIT": "Illuminated",
  "LOG": "Wooden trunk piece",
  "LOT": "Great amount",
  "LOW": "Not high",
  "MAD": "Angry; insane",
  "MAN": "Adult male",
  "MAP": "Area chart",
  "MAT": "Floor covering",
  "MAY": "Possibility word",
  "MEN": "Plural of 'man'",
  "MET": "Encountered",
  "MIX": "Blend together",
  "MOB": "Unruly crowd",
  "MOP": "Floor cleaner",
  "MUD": "Wet earth",
  "MUG": "Coffee cup",
  "NAP": "Brief sleep",
  "NET": "Catching mesh",
  "NEW": "Recently made",
  "NIT": "Louse egg",
  "NOD": "Head bob of agreement",
  "NOR": "Negative conjunction",
  "NOT": "Word of denial",
  "NOW": "At this moment",
  "NUN": "Convent sister",
  "NUT": "Hard-shelled seed",
  "OAK": "Sturdy shade tree",
  "OAR": "Rowing blade",
  "OAT": "Cereal grain",
  "ODD": "Strange; not even",
  "ODE": "Lyric poem",
  "OLD": "Not young",
  "ONE": "Single digit",
  "OPT": "Choose; select",
  "ORB": "Sphere; globe",
  "ORE": "Mineral deposit",
  "OUR": "Belonging to us",
  "OUT": "Not inside",
  "OWE": "Be in debt",
  "OWL": "Nocturnal bird",
  "OWN": "Possess",
  "PAD": "Cushioned surface",
  "PAN": "Cooking vessel",
  "PAT": "Gentle tap",
  "PAW": "Animal foot",
  "PEA": "Small green veggie",
  "PEN": "Writing instrument",
  "PET": "Domestic animal",
  "PIE": "Baked pastry",
  "PIG": "Farm animal",
  "PIN": "Sharp fastener",
  "PIT": "Deep hole",
  "POD": "Pea container",
  "POP": "Burst; soda",
  "POT": "Cooking container",
  "PUT": "Place somewhere",
  "RAG": "Torn cloth",
  "RAM": "Male sheep",
  "RAN": "Sprinted",
  "RAT": "Rodent pest",
  "RAW": "Uncooked",
  "RAY": "Beam of light",
  "RED": "Color of roses",
  "RIB": "Chest bone",
  "RID": "Free from",
  "RIG": "Truck; setup",
  "RIM": "Edge of a cup",
  "RIP": "Tear apart",
  "ROB": "Steal from",
  "ROD": "Fishing pole",
  "ROT": "Decay",
  "ROW": "Line; quarrel",
  "RUB": "Massage; polish",
  "RUG": "Floor carpet",
  "RUN": "Sprint; operate",
  "RUT": "Groove; routine",
  "SAD": "Unhappy",
  "SAP": "Tree fluid",
  "SAT": "Was seated",
  "SAW": "Cutting tool",
  "SAY": "Speak words",
  "SEA": "Salty body of water",
  "SET": "Group; put in place",
  "SEW": "Stitch fabric",
  "SHE": "Female pronoun",
  "SIT": "Take a seat",
  "SIX": "Half a dozen",
  "SKI": "Snow sport",
  "SKY": "The heavens above",
  "SLY": "Crafty; cunning",
  "SOB": "Cry loudly",
  "SOD": "Grass turf",
  "SON": "Male offspring",
  "SOP": "Something soaked",
  "SOT": "Heavy drinker",
  "SPA": "Wellness retreat",
  "SPY": "Secret agent",
  "STY": "Pig enclosure",
  "SUM": "Total amount",
  "SUN": "Our nearest star",
  "TAB": "Running bill",
  "TAG": "Label; marker",
  "TAN": "Brown from sun",
  "TAP": "Light knock",
  "TAR": "Road coating",
  "TEA": "Hot beverage",
  "TEN": "Decimal base",
  "THE": "Most common article",
  "TIE": "Knot; necktie",
  "TIN": "Metal container",
  "TIP": "Gratuity; hint",
  "TOE": "Foot digit",
  "TON": "Heavy weight unit",
  "TOO": "Also; excessively",
  "TOP": "Highest point",
  "TOW": "Pull along",
  "TOY": "Child's plaything",
  "TUB": "Bathing vessel",
  "TUG": "Pull hard",
  "TWO": "Pair number",
  "URN": "Decorative vase",
  "USE": "Employ; utilize",
  "VAN": "Delivery vehicle",
  "VAT": "Large tank",
  "VET": "Animal doctor",
  "VIA": "By way of",
  "VIE": "Compete for",
  "VOW": "Solemn promise",
  "WAR": "Armed conflict",
  "WAS": "Past tense of 'is'",
  "WAX": "Candle material",
  "WAY": "Path; method",
  "WEB": "Spider's creation",
  "WED": "Marry",
  "WET": "Not dry",
  "WHO": "Which person?",
  "WIG": "False hair",
  "WIN": "Victory",
  "WIT": "Clever humor",
  "WOE": "Great sorrow",
  "WOK": "Asian cooking pan",
  "WON": "Was victorious",
  "WOO": "Court; romance",
  "WOW": "Expression of awe",
  "YAM": "Sweet potato",
  "YAP": "Small dog bark",
  "YAW": "Veer off course",
  "YEN": "Japanese currency",
  "YES": "Affirmative answer",
  "YET": "Still; however",
  "YEW": "Evergreen tree",
  "ZAP": "Shock; blast",
  "ZEN": "Peaceful meditation",
  "ZIP": "Zipper; move fast",
  "ZIT": "Skin blemish",
  "ZOO": "Animal park",
  // 4 letters
  "ACRE": "Land measure",
  "ARCH": "Curved doorway",
  "AREA": "Region; zone",
  "ARTS": "Creative works",
  "AXLE": "Wheel rod",
  "BADE": "Commanded; told",
  "BALE": "Hay bundle",
  "BANE": "Source of trouble",
  "BARE": "Uncovered; naked",
  "BARN": "Farm building",
  "BASE": "Foundation; bottom",
  "BEAD": "Tiny ornament",
  "BEAM": "Light ray; timber",
  "BEAR": "Forest mammal",
  "BEAT": "Rhythm; defeat",
  "BEND": "Curve; flex",
  "BEST": "Finest; top",
  "BIKE": "Two-wheeled ride",
  "BIND": "Tie together",
  "BIRD": "Feathered flyer",
  "BITE": "Chomp; nibble",
  "BLOW": "Gust; strike",
  "BLUE": "Sky color",
  "BOAT": "Water vessel",
  "BOLD": "Brave; daring",
  "BOLT": "Lightning flash; fastener",
  "BONE": "Skeletal part",
  "BOOT": "Footwear",
  "BORE": "Drill; be dull",
  "BORN": "Brought into life",
  "BOWL": "Cereal dish",
  "BRED": "Raised animals",
  "BURN": "Fire damage",
  "CAGE": "Animal enclosure",
  "CAKE": "Birthday dessert",
  "CALM": "Peaceful; still",
  "CAME": "Arrived",
  "CAMP": "Outdoor lodging",
  "CANE": "Walking stick",
  "CAPE": "Superhero garment",
  "CARD": "Playing ___; greeting ___",
  "CARE": "Concern; tend to",
  "CART": "Shopping ___",
  "CASE": "Situation; container",
  "CAST": "Throw; actors",
  "CAVE": "Rock hollow",
  "CLAM": "Shellfish",
  "CLAP": "Applause",
  "CLAY": "Potter's material",
  "CLIP": "Fastener; trim",
  "COAL": "Fossil fuel",
  "COAT": "Outer garment",
  "CODE": "Secret cipher",
  "COIN": "Metal currency",
  "COLD": "Low temperature",
  "COLT": "Young horse",
  "CONE": "Ice cream holder",
  "COOK": "Prepare food",
  "COOL": "Slightly cold",
  "COPE": "Deal with difficulty",
  "CORD": "Rope; wire",
  "CORE": "Center; apple part",
  "CORK": "Wine bottle stopper",
  "CORN": "Yellow vegetable",
  "COST": "Price; expense",
  "CREW": "Team; ship workers",
  "CROP": "Farm harvest",
  "CURE": "Remedy; heal",
  "DALE": "Valley",
  "DAME": "Noble lady",
  "DARE": "Challenge boldly",
  "DARK": "Absence of light",
  "DART": "Thrown projectile",
  "DAWN": "Sunrise; daybreak",
  "DEAL": "Bargain; agreement",
  "DEAR": "Beloved; precious",
  "DECK": "Ship floor; card set",
  "DEED": "Action; legal document",
  "DEEM": "Consider; judge",
  "DEEP": "Far below surface",
  "DEER": "Forest animal",
  "DIAL": "Phone face; rotate",
  "DICE": "Gambling cubes",
  "DINE": "Eat a meal",
  "DIRE": "Desperately serious",
  "DISH": "Plate; recipe",
  "DOCK": "Ship berth",
  "DOME": "Rounded roof",
  "DONE": "Finished",
  "DOOM": "Terrible fate",
  "DOOR": "Room entrance",
  "DOSE": "Medicine amount",
  "DOVE": "Peace bird",
  "DOWN": "Toward the ground",
  "DRAW": "Sketch; tie game",
  "DROP": "Fall; bead of liquid",
  "DRUM": "Percussion instrument",
  "DUAL": "Having two parts",
  "DUCK": "Pond bird",
  "DUEL": "One-on-one fight",
  "DUKE": "Noble rank",
  "DULL": "Not sharp; boring",
  "DUNE": "Sand hill",
  "DUST": "Fine particles",
  "DUTY": "Obligation",
  "EACH": "Every one",
  "EARL": "Noble title",
  "EARN": "Deserve; make money",
  "EASE": "Comfort; simplicity",
  "EAST": "Sunrise direction",
  "EASY": "Not difficult",
  "EDGE": "Border; margin",
  "EDIT": "Revise text",
  "ELSE": "Otherwise",
  "EMIT": "Send out; release",
  "EPIC": "Grand; heroic story",
  "EVEN": "Level; divisible by two",
  "EVER": "At any time",
  "EVIL": "Wicked; sinister",
  "EXAM": "Test; assessment",
  "FADE": "Gradually vanish",
  "FAIL": "Not succeed",
  "FAIR": "Just; carnival",
  "FAKE": "Not genuine",
  "FALL": "Autumn; tumble",
  "FAME": "Celebrity status",
  "FARE": "Ticket price",
  "FARM": "Agricultural land",
  "FAST": "Quick; speedy",
  "FATE": "Destiny",
  "FAWN": "Young deer",
  "FEAR": "Dread; phobia",
  "FEAT": "Remarkable deed",
  "FEED": "Give food to",
  "FEEL": "Sense by touch",
  "FELL": "Tumbled down",
  "FELT": "Past of 'feel'; fabric",
  "FERN": "Green plant",
  "FILE": "Folder; smooth",
  "FILL": "Make full",
  "FILM": "Movie; thin layer",
  "FIND": "Discover; locate",
  "FINE": "Excellent; penalty",
  "FIRE": "Flames; blaze",
  "FIRM": "Solid; company",
  "FISH": "Aquatic creature",
  "FIST": "Clenched hand",
  "FLAG": "National banner",
  "FLAT": "Level surface",
  "FLAW": "Defect; imperfection",
  "FLED": "Ran away",
  "FLEW": "Past tense of 'fly'",
  "FLIP": "Turn over quickly",
  "FLOW": "Move like water",
  "FOAM": "Bubbly froth",
  "FOLD": "Bend over",
  "FOLK": "People; traditional",
  "FOND": "Affectionate toward",
  "FOOD": "Nourishment",
  "FOOL": "Silly person",
  "FOOT": "Walking body part",
  "FORD": "River crossing",
  "FORE": "Front; golf warning",
  "FORK": "Eating utensil",
  "FORM": "Shape; document",
  "FORT": "Military stronghold",
  "FOUL": "Offensive; rule break",
  "FOUR": "Number after three",
  "FREE": "Without cost",
  "FROG": "Pond amphibian",
  "FROM": "Starting point",
  "FUEL": "Energy source",
  "FULL": "Completely filled",
  "FUND": "Money source",
  "FUSE": "Electrical safety device",
  "FUSS": "Unnecessary worry",
  "GAIN": "Acquire; profit",
  "GALE": "Strong wind",
  "GAME": "Fun competition",
  "GATE": "Fence entrance",
  "GAVE": "Donated; handed over",
  "GAZE": "Stare intently",
  "GEAR": "Equipment; cog",
  "GENE": "DNA unit",
  "GIFT": "Present; talent",
  "GIST": "Main point",
  "GIVE": "Hand over",
  "GLAD": "Happy; pleased",
  "GLOW": "Soft light",
  "GLUE": "Adhesive",
  "GOAT": "Mountain climber",
  "GOLD": "Precious metal",
  "GOLF": "Club sport",
  "GONE": "Departed",
  "GOOD": "Not bad; virtuous",
  "GRAB": "Seize quickly",
  "GRAY": "Between black and white",
  "GREW": "Got bigger",
  "GRID": "Network of lines",
  "GRIN": "Big smile",
  "GRIP": "Firm hold",
  "GROW": "Increase in size",
  "GULF": "Coastal inlet",
  "GUST": "Sudden wind",
  "HAIL": "Ice pellets; greet",
  "HAIR": "Head strands",
  "HALE": "Healthy; robust",
  "HALF": "Fifty percent",
  "HALL": "Corridor; large room",
  "HALT": "Stop completely",
  "HAND": "Body's grasping part",
  "HANG": "Suspend from above",
  "HARD": "Not soft; difficult",
  "HARE": "Fast rabbit",
  "HARM": "Damage; injury",
  "HARP": "Stringed instrument",
  "HASH": "Chopped mixture",
  "HATE": "Intense dislike",
  "HAUL": "Pull heavily",
  "HAVE": "Possess; own",
  "HAZE": "Thin fog",
  "HEAD": "Top of body",
  "HEAL": "Cure; recover",
  "HEAP": "Pile of things",
  "HEAR": "Perceive sound",
  "HEAT": "Warmth; temperature",
  "HEEL": "Back of foot",
  "HELD": "Grasped; kept",
  "HELP": "Assist; aid",
  "HERE": "In this place",
  "HERO": "Brave person",
  "HIDE": "Conceal; animal skin",
  "HIGH": "Far above ground",
  "HIKE": "Long walk outdoors",
  "HILL": "Small mountain",
  "HINT": "Subtle clue",
  "HIRE": "Employ someone",
  "HOLD": "Grasp; contain",
  "HOLE": "Opening; cavity",
  "HOME": "Where one lives",
  "HONE": "Sharpen; perfect",
  "HOOD": "Head covering",
  "HOOK": "Curved fastener",
  "HOPE": "Wish; desire",
  "HORN": "Animal feature; trumpet",
  "HOSE": "Garden watering tube",
  "HOST": "Party organizer",
  "HOUR": "Sixty minutes",
  "HUGE": "Enormously big",
  "HULL": "Ship's body",
  "HUNT": "Search for prey",
  "HURT": "Cause pain",
  "HYMN": "Religious song",
  "IDEA": "Thought; concept",
  "IDLE": "Not working; lazy",
  "IRON": "Pressing appliance; metal",
  "ISLE": "Small island",
  "ITEM": "Individual thing",
  "JADE": "Green gemstone",
  "JAIL": "Prison",
  "JEST": "Joke; wisecrack",
  "JOKE": "Funny story",
  "JOLT": "Sudden shock",
  "JUMP": "Leap into the air",
  "JURY": "Trial panel",
  "JUST": "Fair; only",
  "KEEN": "Eager; sharp",
  "KEEP": "Retain; hold onto",
  "KEPT": "Retained",
  "KICK": "Strike with foot",
  "KIDS": "Children",
  "KILL": "End life of",
  "KIND": "Gentle; type",
  "KING": "Male monarch",
  "KITE": "Flying toy",
  "KNIT": "Make with yarn",
  "KNOB": "Door handle",
  "KNOT": "Tied rope",
  "KNOW": "Have knowledge of",
  "LACE": "Decorative fabric",
  "LACK": "Be without",
  "LAID": "Put down",
  "LAKE": "Inland water body",
  "LAMB": "Young sheep",
  "LAME": "Unable to walk well",
  "LAMP": "Light source",
  "LAND": "Solid ground",
  "LANE": "Narrow road",
  "LARD": "Cooking fat",
  "LARK": "Songbird; adventure",
  "LASH": "Whip; eyelash",
  "LAST": "Final; endure",
  "LATE": "Not on time",
  "LAWN": "Grass yard",
  "LEAD": "Guide; metal",
  "LEAF": "Tree foliage",
  "LEAK": "Drip through crack",
  "LEAN": "Thin; tilt",
  "LEAP": "Jump high",
  "LEFT": "Opposite of right",
  "LEND": "Loan to someone",
  "LENS": "Camera glass",
  "LESS": "Not as much",
  "LIAR": "Untruthful person",
  "LICE": "Head parasites",
  "LIED": "Told an untruth",
  "LIFE": "Being alive",
  "LIFT": "Raise up",
  "LIKE": "Enjoy; similar to",
  "LIMB": "Tree branch; body part",
  "LIME": "Green citrus fruit",
  "LIMP": "Walk unevenly",
  "LINE": "Long thin mark",
  "LINK": "Connection; chain piece",
  "LION": "King of the jungle",
  "LIST": "Written sequence",
  "LIVE": "Be alive; reside",
  "LOAD": "Heavy cargo",
  "LOAF": "Bread unit",
  "LOAN": "Borrowed money",
  "LOCK": "Security device",
  "LOFT": "Upper room; attic",
  "LONE": "Solitary; only",
  "LONG": "Not short",
  "LOOK": "See; glance",
  "LOOP": "Circular shape",
  "LORD": "Noble ruler",
  "LORE": "Traditional knowledge",
  "LOSE": "Not win",
  "LOSS": "The losing of something",
  "LOST": "Unable to find way",
  "LOTS": "Many; great amount",
  "LOUD": "Not quiet",
  "LOVE": "Deep affection",
  "LUCK": "Good fortune",
  "LUMP": "Raised bump",
  "LUNG": "Breathing organ",
  "LURE": "Tempt; bait",
  "MADE": "Created; built",
  "MAIL": "Postal letters",
  "MAIN": "Primary; chief",
  "MAKE": "Create; build",
  "MALE": "Man or boy",
  "MANE": "Horse's neck hair",
  "MARE": "Female horse",
  "MARK": "Visible sign; stain",
  "MASK": "Face covering",
  "MASS": "Large quantity",
  "MAST": "Ship's pole",
  "MATE": "Partner; friend",
  "MAZE": "Confusing network",
  "MEAL": "Breakfast or dinner",
  "MEAN": "Average; unkind",
  "MEAT": "Animal flesh food",
  "MELD": "Blend together",
  "MELT": "Become liquid",
  "MEND": "Repair; fix",
  "MENU": "Food list",
  "MILD": "Gentle; not strong",
  "MILE": "Distance measure",
  "MILK": "Dairy drink",
  "MILL": "Grinding factory",
  "MIND": "Brain; intellect",
  "MINE": "Belonging to me; dig site",
  "MINT": "Fresh herb; coin factory",
  "MISS": "Fail to hit; young lady",
  "MIST": "Light fog",
  "MOAT": "Castle water ditch",
  "MODE": "Method; style",
  "MOLD": "Fungus; shape",
  "MOLE": "Burrowing animal",
  "MOOD": "Emotional state",
  "MOON": "Night sky orb",
  "MOOR": "Tie a boat; heath land",
  "MORE": "Greater amount",
  "MOST": "Greatest amount",
  "MOTH": "Night butterfly",
  "MOVE": "Change position",
  "MUCH": "Great quantity",
  "MULE": "Horse-donkey hybrid",
  "MUST": "Have to; necessity",
  "MUTE": "Silent; soundless",
  "MYTH": "Ancient legend",
  "NAIL": "Hammer fastener",
  "NAME": "What you're called",
  "NAVE": "Church center aisle",
  "NAVY": "Sea military force",
  "NEAR": "Close by",
  "NEAT": "Tidy; orderly",
  "NECK": "Body part below head",
  "NEED": "Require; necessity",
  "NEST": "Bird's home",
  "NEWS": "Current events",
  "NEXT": "Following; adjacent",
  "NICE": "Pleasant; kind",
  "NINE": "Number after eight",
  "NODE": "Connection point",
  "NONE": "Not any",
  "NOON": "Midday; 12 PM",
  "NORM": "Standard; typical",
  "NOSE": "Smell organ",
  "NOTE": "Short message; music tone",
  "NOUN": "Person, place, or thing",
  "NUMB": "Without feeling",
  "OATH": "Solemn promise",
  "OBEY": "Follow orders",
  "ODDS": "Chances; probability",
  "OILS": "Cooking liquids",
  "OMEN": "Sign of things to come",
  "OMIT": "Leave out",
  "ONCE": "One time only",
  "ONLY": "Sole; just",
  "ONTO": "Upon; on top of",
  "OOZE": "Seep slowly",
  "OPEN": "Not closed",
  "ORAL": "Spoken; by mouth",
  "ORCA": "Killer whale",
  "OVEN": "Baking appliance",
  "OVER": "Above; finished",
  "PACE": "Walking speed",
  "PACK": "Bundle; group",
  "PAGE": "Book leaf",
  "PAID": "Compensated",
  "PAIL": "Water bucket",
  "PAIN": "Hurt; suffering",
  "PAIR": "Set of two",
  "PALE": "Light-colored; wan",
  "PALM": "Tropical tree; hand part",
  "PANE": "Window glass",
  "PANT": "Breathe hard",
  "PARK": "Green space",
  "PART": "Portion; piece",
  "PASS": "Go by; mountain gap",
  "PAST": "Previous time",
  "PATH": "Walking trail",
  "PAVE": "Cover with asphalt",
  "PEAK": "Mountain top",
  "PEAR": "Green fruit",
  "PEAT": "Boggy fuel",
  "PEEL": "Remove skin",
  "PEEK": "Quick look",
  "PEER": "Equal; look closely",
  "PEST": "Annoying creature",
  "PICK": "Choose; select",
  "PIER": "Waterfront walkway",
  "PILE": "Stack; heap",
  "PINE": "Evergreen tree",
  "PIPE": "Tube; smoking device",
  "PLAN": "Strategy; blueprint",
  "PLAY": "Have fun; drama",
  "PLEA": "Urgent request",
  "PLOD": "Walk heavily",
  "PLOT": "Story plan; scheme",
  "PLOW": "Farm tilling tool",
  "PLUM": "Purple fruit",
  "PLUS": "Addition; positive",
  "POEM": "Verse composition",
  "POET": "Verse writer",
  "POLE": "Long stick",
  "POLL": "Survey; vote",
  "POND": "Small lake",
  "POOL": "Swimming place",
  "POOR": "Not wealthy",
  "POPE": "Catholic leader",
  "PORE": "Tiny skin opening",
  "PORK": "Pig meat",
  "PORT": "Harbor; left side",
  "POSE": "Stance; pretend",
  "POST": "Mail; pole",
  "POUR": "Flow liquid",
  "PRAY": "Talk to God",
  "PREY": "Hunted animal",
  "PROP": "Support; stage item",
  "PULL": "Tug toward",
  "PUMP": "Move liquid",
  "PURE": "Clean; uncontaminated",
  "PUSH": "Press forward",
  "RACE": "Speed contest",
  "RAFT": "Floating platform",
  "RAGE": "Intense anger",
  "RAID": "Sudden attack",
  "RAIL": "Fence bar; train track",
  "RAIN": "Water from clouds",
  "RAKE": "Leaf-gathering tool",
  "RAMP": "Inclined surface",
  "RANG": "Made a bell sound",
  "RANK": "Position; status",
  "RARE": "Uncommon; scarce",
  "RASH": "Hasty; skin outbreak",
  "RATE": "Speed; price level",
  "RAVE": "Enthusiastic review",
  "READ": "Look at text",
  "REAL": "Genuine; not fake",
  "REAP": "Harvest crops",
  "REED": "Marsh grass",
  "REEF": "Coral formation",
  "REEL": "Fishing spool",
  "REIN": "Horse strap",
  "RELY": "Depend on",
  "RENT": "Monthly payment",
  "REST": "Relax; remainder",
  "RICE": "Asian grain staple",
  "RICH": "Wealthy; abundant",
  "RIDE": "Travel in vehicle",
  "RIND": "Fruit outer skin",
  "RING": "Circular band",
  "RINK": "Ice skating surface",
  "RISE": "Go upward",
  "RISK": "Chance of danger",
  "ROAD": "Paved route",
  "ROAM": "Wander freely",
  "ROBE": "Long flowing garment",
  "ROCK": "Stone; music genre",
  "RODE": "Past tense of 'ride'",
  "ROLE": "Part to play",
  "ROLL": "Bread unit; turn over",
  "ROOF": "House top",
  "ROOM": "Living space",
  "ROOT": "Plant base; cheer",
  "ROPE": "Thick cord",
  "ROSE": "Garden flower",
  "ROTE": "Memorization method",
  "ROVE": "Wander about",
  "RUDE": "Impolite",
  "RUIN": "Destroy; wreckage",
  "RULE": "Regulation; govern",
  "RUNG": "Ladder step",
  "RUSH": "Hurry; marsh plant",
  "RUST": "Iron corrosion",
  "SAFE": "Secure; vault",
  "SAGE": "Wise person; herb",
  "SAID": "Spoke",
  "SAIL": "Boat canvas",
  "SAKE": "Purpose; benefit",
  "SALE": "Discounted event",
  "SALT": "Table seasoning",
  "SAME": "Identical; alike",
  "SAND": "Beach grains",
  "SANE": "Mentally sound",
  "SANG": "Past tense of 'sing'",
  "SANK": "Past tense of 'sink'",
  "SASH": "Window frame; ribbon",
  "SAVE": "Rescue; store",
  "SCAR": "Wound mark",
  "SEAL": "Close up; marine mammal",
  "SEAM": "Sewing line; join",
  "SEED": "Plant starter",
  "SEEK": "Search for",
  "SEEM": "Appear to be",
  "SEEN": "Past participle of 'see'",
  "SELF": "One's own person",
  "SELL": "Exchange for money",
  "SEND": "Mail; dispatch",
  "SENT": "Dispatched",
  "SHED": "Garden outbuilding",
  "SHIN": "Front of lower leg",
  "SHIP": "Large sea vessel",
  "SHOE": "Foot covering",
  "SHOP": "Store; buy things",
  "SHOT": "Fired; attempt",
  "SHOW": "Display; program",
  "SHUT": "Close tightly",
  "SICK": "Ill; unwell",
  "SIDE": "Edge; flank",
  "SIFT": "Strain; sort",
  "SIGH": "Breath of relief",
  "SIGN": "Notice; symbol",
  "SILK": "Smooth fabric",
  "SING": "Vocalize melody",
  "SINK": "Basin; go down",
  "SIRE": "Father; address to king",
  "SITE": "Location; place",
  "SIZE": "Dimensions",
  "SKIM": "Glide over; scan",
  "SKIN": "Body covering",
  "SKIP": "Hop; omit",
  "SLAB": "Thick flat piece",
  "SLAM": "Shut forcefully",
  "SLAP": "Open-hand hit",
  "SLED": "Snow vehicle",
  "SLEW": "Killed; many",
  "SLID": "Moved smoothly",
  "SLIM": "Thin; slender",
  "SLIP": "Slide; error",
  "SLIT": "Narrow cut",
  "SLOT": "Narrow opening",
  "SLOW": "Not fast",
  "SLUG": "Garden pest",
  "SNAP": "Quick break; photo",
  "SNARL": "xxx",
  "SNIP": "Quick cut",
  "SNOW": "White precipitation",
  "SOAK": "Drench; steep",
  "SOAP": "Washing bar",
  "SOAR": "Fly high",
  "SOCK": "Foot garment",
  "SOFT": "Not hard",
  "SOIL": "Earth; dirt",
  "SOLD": "Past tense of 'sell'",
  "SOLE": "Only; shoe bottom",
  "SOME": "A few; partial",
  "SONG": "Musical piece",
  "SOON": "In a short time",
  "SOOT": "Black chimney dust",
  "SORE": "Painful; tender",
  "SORT": "Type; organize",
  "SOUL": "Inner spirit",
  "SOUP": "Hot liquid food",
  "SOUR": "Acidic taste",
  "SPAN": "Bridge length; extent",
  "SPAR": "Box lightly; pole",
  "SPIN": "Rotate quickly",
  "SPIT": "Expel saliva",
  "SPOT": "Location; see",
  "SPUR": "Urge on; boot spike",
  "STAB": "Pierce with knife",
  "STAR": "Night sky sparkle",
  "STAY": "Remain in place",
  "STEM": "Plant stalk",
  "STEP": "Foot movement",
  "STEW": "Slow-cooked dish",
  "STIR": "Mix with spoon",
  "STOP": "Cease; halt",
  "STUD": "Earring type; wall beam",
  "STUN": "Shock; amaze",
  "SUCH": "Of that kind",
  "SUIT": "Formal outfit",
  "SURE": "Certain; of course",
  "SURF": "Ride ocean waves",
  "SWAN": "Elegant water bird",
  "SWAP": "Trade; exchange",
  "SWIM": "Water exercise",
  "TABS": "Browser windows",
  "TACK": "Small nail; direction",
  "TAIL": "Animal back end",
  "TAKE": "Grab; seize",
  "TALE": "Story; narrative",
  "TALL": "High in stature",
  "TAME": "Domesticated",
  "TANK": "Large container",
  "TAPE": "Adhesive strip",
  "TARP": "Protective cover",
  "TASK": "Job; duty",
  "TEAM": "Group of players",
  "TEAR": "Rip; eye drop",
  "TELL": "Inform; speak",
  "TEND": "Look after; lean toward",
  "TENT": "Camping shelter",
  "TERM": "Time period; word",
  "TEST": "Exam; trial",
  "TEXT": "Written words",
  "THAN": "Comparison word",
  "THAT": "Demonstrative pronoun",
  "THEM": "Those people",
  "THEN": "After that",
  "THEY": "Those people (subject)",
  "THIN": "Not thick",
  "THIS": "Current item",
  "TIDE": "Ocean rise and fall",
  "TIDY": "Neat; clean up",
  "TIED": "Fastened; equal score",
  "TIER": "Row; level",
  "TILE": "Floor square",
  "TILL": "Until; farm",
  "TILT": "Lean; slant",
  "TIME": "Clock measure",
  "TINT": "Light color shade",
  "TINY": "Very small",
  "TIRE": "Wheel rubber",
  "TOAD": "Warty amphibian",
  "TOIL": "Hard labor",
  "TOLD": "Past tense of 'tell'",
  "TOLL": "Bell sound; fee",
  "TOMB": "Burial chamber",
  "TONE": "Sound quality; shade",
  "TOOK": "Past tense of 'take'",
  "TOOL": "Work instrument",
  "TOPS": "Highest points",
  "TORE": "Ripped apart",
  "TORN": "Ripped; damaged",
  "TOUR": "Sightseeing trip",
  "TOWN": "Small city",
  "TRAP": "Snare; catch",
  "TRAY": "Serving platform",
  "TREE": "Woody plant",
  "TREK": "Long journey",
  "TRIM": "Cut neatly",
  "TRIO": "Group of three",
  "TRIP": "Journey; stumble",
  "TROD": "Walked on",
  "TROT": "Jogging pace",
  "TRUE": "Not false",
  "TUBE": "Hollow cylinder",
  "TUCK": "Push into place",
  "TUFT": "Cluster; clump",
  "TULIP": "Spring flower",
  "TUNE": "Melody; adjust",
  "TURF": "Grass surface",
  "TURN": "Rotate; change direction",
  "TWIN": "Identical sibling",
  "TYPE": "Kind; keyboard",
  "UGLY": "Unattractive",
  "UNIT": "Single measure",
  "UPON": "On top of",
  "USED": "Not new; employed",
  "USER": "Someone who uses",
  "VAIN": "Conceited; useless",
  "VALE": "Valley",
  "VANE": "Wind direction indicator",
  "VARY": "Change; differ",
  "VASE": "Flower holder",
  "VAST": "Huge; immense",
  "VEIL": "Face covering",
  "VEIN": "Blood vessel",
  "VENT": "Air opening",
  "VERB": "Action word",
  "VERY": "Extremely",
  "VEST": "Sleeveless garment",
  "VETO": "Reject; forbid",
  "VIEW": "Scene; opinion",
  "VINE": "Grape plant",
  "VOID": "Empty space",
  "VOLT": "Electrical unit",
  "VOTE": "Cast a ballot",
  "WADE": "Walk through water",
  "WAGE": "Pay; salary",
  "WAIL": "Cry loudly",
  "WAIT": "Stay in place",
  "WAKE": "Stop sleeping",
  "WALK": "Stroll on foot",
  "WALL": "Room divider",
  "WAND": "Magic stick",
  "WANT": "Desire; wish for",
  "WARD": "Hospital section",
  "WARM": "Comfortably hot",
  "WARN": "Alert to danger",
  "WARP": "Bend out of shape",
  "WART": "Skin bump",
  "WASH": "Clean with water",
  "WASP": "Stinging insect",
  "WAVE": "Ocean swell; greeting",
  "WAYS": "Methods",
  "WEAK": "Not strong",
  "WEAR": "Put on clothes",
  "WEED": "Unwanted plant",
  "WEEK": "Seven days",
  "WEEP": "Cry softly",
  "WELD": "Fuse metals",
  "WELL": "Water source; healthy",
  "WENT": "Past tense of 'go'",
  "WERE": "Past tense of 'are'",
  "WEST": "Sunset direction",
  "WHAT": "Which thing?",
  "WHEN": "At what time?",
  "WHOM": "Object form of 'who'",
  "WICK": "Candle string",
  "WIDE": "Not narrow",
  "WIFE": "Married woman",
  "WILD": "Untamed",
  "WILL": "Future tense; testament",
  "WILT": "Droop; wither",
  "WILY": "Crafty; clever",
  "WIMP": "Timid person",
  "WIND": "Air movement",
  "WINE": "Grape beverage",
  "WING": "Bird's flight limb",
  "WINK": "Eye blink",
  "WIPE": "Clean by rubbing",
  "WIRE": "Metal strand",
  "WISE": "Full of wisdom",
  "WISH": "Heart's desire",
  "WITH": "Accompanied by",
  "WOKE": "Became alert",
  "WOLF": "Wild canine",
  "WOOD": "Tree material",
  "WOOL": "Sheep fiber",
  "WORD": "Language unit",
  "WORE": "Past tense of 'wear'",
  "WORK": "Job; labor",
  "WORM": "Soil crawler",
  "WORN": "Used; weathered",
  "WRAP": "Cover up",
  "WREN": "Small songbird",
  "YARD": "Lawn; three feet",
  "YARN": "Knitting thread",
  "YEAR": "365 days",
  "YELL": "Shout loudly",
  "YOKE": "Oxen collar",
  "YOUR": "Belonging to you",
  "ZEAL": "Enthusiastic passion",
  "ZERO": "Nothing; nil",
  "ZONE": "Designated area",
  "ZOOM": "Move fast; lens",
  // 5 letters
  "ABOVE": "Higher than",
  "ADMIT": "Confess; allow in",
  "ADORE": "Love deeply",
  "ADULT": "Grown person",
  "AGILE": "Quick and nimble",
  "ALERT": "Watchful warning",
  "ALIGN": "Line up properly",
  "ANGER": "Fury; wrath",
  "ANGLE": "Corner; viewpoint",
  "ARENA": "Stadium; contest venue",
  "ARISE": "Stand up; occur",
  "ASIDE": "To one side",
  "BASIC": "Fundamental",
  "BATCH": "Group; set",
  "BEARS": "Forest mammals",
  "BEAST": "Wild animal",
  "BEGIN": "Start",
  "BELOW": "Under; beneath",
  "BIRTH": "Coming into life",
  "BLADE": "Knife edge; grass leaf",
  "BLAME": "Hold responsible",
  "BLAND": "Dull; tasteless",
  "BLANK": "Empty space",
  "BLAZE": "Bright fire",
  "BLEED": "Lose blood",
  "BLEND": "Mix together",
  "BLESS": "Give divine favor",
  "BLISS": "Perfect happiness",
  "BLOCK": "Cube; obstruct",
  "BLOOM": "Flower opening",
  "BLOWN": "Past of 'blow'",
  "BLUNT": "Not sharp",
  "BOARD": "Plank; committee",
  "BOAST": "Brag; show off",
  "BONUS": "Extra reward",
  "BOUND": "Tied; limit",
  "BRAVE": "Courageous; bold",
  "BREAD": "Staple baked food",
  "BREAK": "Shatter; rest",
  "BREED": "Animal type; raise",
  "BRICK": "Building block",
  "BRIDE": "Wedding woman",
  "BRIEF": "Short; concise",
  "BRING": "Carry to",
  "BROAD": "Wide; extensive",
  "BROKE": "Shattered; penniless",
  "BROOD": "Ponder; bird family",
  "BROOK": "Small stream",
  "BRUSH": "Hair tool; shrubs",
  "BUILD": "Construct; create",
  "BURNS": "Fire injuries; Scottish poet",
  "BURST": "Explode; pop",
  "CABIN": "Rustic shelter",
  "CABLE": "Thick wire",
  "CAMEL": "Desert animal",
  "CARGO": "Ship's freight",
  "CARRY": "Hold and transport",
  "CARVE": "Cut into shape",
  "CATCH": "Grab; capture",
  "CAUSE": "Reason; bring about",
  "CEDAR": "Aromatic wood tree",
  "CHAIN": "Metal links",
  "CHAIR": "Seat with back",
  "CHALK": "Writing stick",
  "CHARM": "Attraction; spell",
  "CHASE": "Pursue; run after",
  "CHEAP": "Not expensive",
  "CHECK": "Verify; mark",
  "CHEER": "Shout of joy",
  "CHESS": "Strategy board game",
  "CHIEF": "Leader; head",
  "CHILD": "Young person",
  "CHILL": "Cold feeling",
  "CHOIR": "Singing group",
  "CLAIM": "Assert; demand",
  "CLAMP": "Tightening tool",
  "CLASS": "Lesson; group",
  "CLEAN": "Not dirty",
  "CLEAR": "Transparent; obvious",
  "CLERK": "Office worker",
  "CLIMB": "Go upward",
  "CLING": "Hold on tight",
  "CLOCK": "Time device",
  "CLOSE": "Shut; near",
  "CLOTH": "Woven fabric",
  "CLOUD": "Sky formation",
  "COACH": "Trainer; bus",
  "COAST": "Shoreline",
  "COLOR": "Hue; shade",
  "COMET": "Celestial ice body",
  "CORAL": "Reef material",
  "COULD": "Past tense of 'can'",
  "COUNT": "Number; tally",
  "COURT": "Legal arena; yard",
  "COVER": "Hide; blanket",
  "CRACK": "Split; fissure",
  "CRAFT": "Skill; trade; boat",
  "CRANE": "Bird; lifting machine",
  "CRASH": "Collision; break",
  "CRAWL": "Move on hands and knees",
  "CRAZY": "Insane; wild",
  "CREAM": "Dairy topping",
  "CREEK": "Small stream",
  "CREST": "Hilltop; emblem",
  "CRISP": "Crunchy; sharp",
  "CROSS": "Angry; intersection",
  "CROWD": "Large group of people",
  "CROWN": "Royal headpiece",
  "CRUSH": "Squash; infatuation",
  "CRUST": "Bread outer layer",
  "CURVE": "Bend; arc",
  "CYCLE": "Recurring period",
  "DAILY": "Every day",
  "DANCE": "Move to music",
  "DEATH": "End of life",
  "DECAY": "Rot; decompose",
  "DECOR": "Room decoration",
  "DEMON": "Evil spirit",
  "DENSE": "Thick; packed",
  "DEPTH": "Deepness",
  "DIARY": "Personal journal",
  "DIGIT": "Number; finger",
  "DITCH": "Drainage trench",
  "DIZZY": "Lightheaded; spinning",
  "DODGE": "Avoid; duck",
  "DOING": "Performing an action",
  "DOUBT": "Uncertainty",
  "DOUGH": "Bread mixture",
  "DRAFT": "Rough copy; air current",
  "DRAIN": "Empty of liquid",
  "DRAKE": "Male duck",
  "DRAPE": "Hang cloth",
  "DRAWN": "Sketched; pulled",
  "DREAD": "Great fear",
  "DREAM": "Sleep vision; aspire",
  "DRESS": "Garment; put on clothes",
  "DRIED": "Removed moisture",
  "DRIFT": "Float; move slowly",
  "DRILL": "Boring tool; practice",
  "DRINK": "Beverage; consume liquid",
  "DRIVE": "Operate a car",
  "DROVE": "Past of 'drive'; herd",
  "DRUNK": "Intoxicated",
  "DWARF": "Small mythical being",
  "DWELL": "Live; reside",
  "EAGER": "Enthusiastic; keen",
  "EAGLE": "Majestic bird of prey",
  "EARLY": "Before expected time",
  "EARTH": "Our planet; soil",
  "EASEL": "Painter's stand",
  "EIGHT": "Number after seven",
  "ELDER": "Older person",
  "ELECT": "Choose by vote",
  "EMPTY": "Containing nothing",
  "ENEMY": "Foe; opponent",
  "ENJOY": "Take pleasure in",
  "ENTER": "Go inside",
  "EQUAL": "The same in value",
  "ERASE": "Delete; rub out",
  "ERROR": "Mistake",
  "EVENT": "Happening; occasion",
  "EVERY": "Each one",
  "EXACT": "Precise; accurate",
  "EXILE": "Forced absence",
  "EXIST": "Be; have reality",
  "EXTRA": "Additional; bonus",
  "FABLE": "Moral story",
  "FAITH": "Trust; belief",
  "FALSE": "Not true",
  "FEAST": "Large meal",
  "FENCE": "Yard barrier",
  "FERRY": "Boat transport",
  "FETCH": "Go get; retrieve",
  "FIELD": "Open land; area",
  "FIEND": "Evil person",
  "FIGHT": "Battle; struggle",
  "FINAL": "Last; ultimate",
  "FIRST": "Before all others",
  "FLAME": "Fire tongue",
  "FLASH": "Quick light burst",
  "FLASK": "Small bottle",
  "FLEET": "Group of ships",
  "FLESH": "Body tissue",
  "FLOAT": "Stay on water surface",
  "FLOCK": "Group of birds",
  "FLOOD": "Water overflow",
  "FLOOR": "Room bottom",
  "FLOUR": "Baking powder",
  "FLOWN": "Past of 'fly'",
  "FLUID": "Liquid; flowing",
  "FLUSH": "Blush; rinse",
  "FLUTE": "Woodwind instrument",
  "FOCUS": "Concentrate; center",
  "FOGGY": "Misty; unclear",
  "FORCE": "Power; compel",
  "FORGE": "Create; metalwork",
  "FOUND": "Discovered; establish",
  "FRAME": "Border; structure",
  "FRESH": "New; recently made",
  "FRONT": "Forward part",
  "FROST": "Thin ice layer",
  "FROZE": "Became ice",
  "FRUIT": "Sweet plant food",
  "GAUGE": "Measure; meter",
  "GHOST": "Spirit; phantom",
  "GIANT": "Huge being",
  "GIVEN": "Donated; assumed",
  "GLADE": "Forest clearing",
  "GLEAM": "Faint light",
  "GLIDE": "Move smoothly",
  "GLOBE": "Round sphere; world",
  "GLOOM": "Darkness; sadness",
  "GLOSS": "Shine; polish",
  "GRAIN": "Cereal seed",
  "GRAND": "Magnificent; 1000",
  "GRANT": "Give; award",
  "GRAPE": "Wine fruit",
  "GRASP": "Firm grip",
  "GRASS": "Green lawn cover",
  "GRATE": "Shred; fireplace",
  "GRAVE": "Burial site",
  "GRAZE": "Feed on grass",
  "GREAT": "Very good; large",
  "GREED": "Excessive desire",
  "GREEN": "Color of grass",
  "GREET": "Welcome; say hello",
  "GRIEF": "Deep sorrow",
  "GRILL": "Cook on open flame",
  "GRIND": "Crush to powder",
  "GROVE": "Small group of trees",
  "GROWL": "Deep angry sound",
  "GROWN": "Fully developed",
  "GUARD": "Protect; sentry",
  "GUESS": "Estimate; suppose",
  "GUIDE": "Leader; handbook",
  "GUILT": "Feeling of blame",
  "HABIT": "Regular practice",
  "HARSH": "Rough; severe",
  "HASTE": "Urgency; hurry",
  "HAUNT": "Visit as a ghost",
  "HAVEN": "Safe place",
  "HEART": "Love organ; center",
  "HEAVY": "Not light; weighty",
  "HEDGE": "Garden border bush",
  "HEIST": "Robbery; theft",
  "HERBS": "Cooking plants",
  "HOIST": "Lift up",
  "HONEY": "Bee's sweet product",
  "HONOR": "Respect; glory",
  "HORSE": "Riding animal",
  "HOTEL": "Lodging place",
  "HOUND": "Hunting dog",
  "HOUSE": "Dwelling; home",
  "HUMAN": "Person; mortal",
  "HUMOR": "Funny quality",
  "HURRY": "Rush; be quick",
  "IMAGE": "Picture; likeness",
  "INDEX": "Alphabetical list",
  "INNER": "Interior; inside",
  "INPUT": "Data entered",
  "IVORY": "Tusk material",
  "JEWEL": "Precious stone",
  "JOKER": "Wild card; jester",
  "JUICE": "Fruit drink",
  "KARMA": "Cosmic justice",
  "KAYAK": "Paddling boat",
  "KNOCK": "Rap on door",
  "KNOWN": "Recognized; famous",
  "LABEL": "Tag; name",
  "LATER": "After a while",
  "LAYER": "Single thickness",
  "LEASH": "Dog lead",
  "LEAVE": "Depart; go away",
  "LEGAL": "Lawful; permitted",
  "LEVEL": "Flat; even surface",
  "LEVER": "Lifting bar",
  "LIGHT": "Illumination",
  "LIMIT": "Boundary; cap",
  "LINEN": "Fabric from flax",
  "LIVER": "Body organ",
  "LODGE": "Cabin; temporary stay",
  "LOGIC": "Reason; rational thought",
  "LOOSE": "Not tight",
  "LOVER": "Romantic partner",
  "LOWER": "Reduce; below",
  "LUNAR": "Of the moon",
  "LUNGE": "Quick thrust",
  "MAGIC": "Supernatural power",
  "MAJOR": "Significant; army rank",
  "MANOR": "Large estate",
  "MAPLE": "Syrup tree",
  "MARCH": "Walk in formation; month",
  "MARSH": "Wetland; swamp",
  "MATCH": "Game; fire stick; pair",
  "MAYOR": "City leader",
  "MEDAL": "Award disk",
  "MERCY": "Compassion; pity",
  "MINER": "Underground worker",
  "MINOR": "Small; not major",
  "MIRTH": "Merriment; laughter",
  "MODEL": "Copy; fashion ___",
  "MONEY": "Currency; cash",
  "MONTH": "Calendar division",
  "MORAL": "Lesson; ethical",
  "MOUNT": "Climb; mountain",
  "MOUSE": "Small rodent",
  "MOUTH": "Oral opening",
  "MOVIE": "Film; cinema show",
  "MURAL": "Wall painting",
  "MUSIC": "Melodic art form",
  "NAVAL": "Of the navy",
  "NERVE": "Body signal wire",
  "NEVER": "Not ever; at no time",
  "NIGHT": "Dark hours",
  "NOBLE": "Aristocratic; worthy",
  "NOISE": "Loud sound",
  "NORTH": "Compass direction",
  "NOVEL": "Book; new",
  "NURSE": "Medical caretaker",
  "OASIS": "Desert water spot",
  "OCEAN": "Vast sea",
  "OLIVE": "Green or black fruit",
  "OPERA": "Singing drama",
  "ORDER": "Arrangement; command",
  "ORGAN": "Body part; instrument",
  "OTHER": "Different one",
  "OUTER": "External",
  "OXIDE": "Rust compound",
  "PAINT": "Color coating",
  "PANEL": "Board; committee group",
  "PAPER": "Writing sheets",
  "PASTE": "Glue; adhesive",
  "PATCH": "Repair piece",
  "PAUSE": "Brief stop",
  "PEACE": "Calm; no war",
  "PEACH": "Fuzzy stone fruit",
  "PEARL": "Oyster gem",
  "PHASE": "Stage; period",
  "PIANO": "Keyboard instrument",
  "PIECE": "Portion; fragment",
  "PILOT": "Aircraft driver",
  "PITCH": "Throw; music frequency",
  "PLACE": "Location; spot",
  "PLAID": "Checkered pattern",
  "PLAIN": "Simple; flat land",
  "PLANE": "Aircraft; flat surface",
  "PLANT": "Growing organism",
  "PLATE": "Dinner dish",
  "PLEAD": "Beg; argue in court",
  "PLUMB": "Vertical; drain fix",
  "PLUME": "Large feather",
  "PLUMP": "Slightly fat",
  "PLUNGE": "Dive in",
  "POINT": "Sharp end; location",
  "POLAR": "Of the poles",
  "PORCH": "House entrance area",
  "POUND": "British currency; hit",
  "POWER": "Strength; energy",
  "PRESS": "Push; news media",
  "PRICE": "Cost; value",
  "PRIDE": "Self-respect",
  "PRIME": "Best; first",
  "PRINT": "Published copy",
  "PRIOR": "Before; earlier",
  "PRIZE": "Award; reward",
  "PROOF": "Evidence; verification",
  "PROUD": "Full of pride",
  "PROVE": "Show to be true",
  "PSALM": "Sacred song",
  "PUNCH": "Hit with fist",
  "PURSE": "Handbag",
  "QUEEN": "Female monarch",
  "QUEST": "Search; mission",
  "QUICK": "Fast; speedy",
  "QUIET": "Not noisy",
  "QUILL": "Feather pen",
  "QUOTE": "Repeat words",
  "RADAR": "Detection system",
  "RADIO": "Broadcast receiver",
  "RAISE": "Lift up; increase",
  "RALLY": "Gathering; recovery",
  "RANCH": "Large farm",
  "RANGE": "Extent; stove",
  "RAPID": "Very fast",
  "REACH": "Extend to; arrive",
  "REALM": "Kingdom; domain",
  "REIGN": "Royal rule",
  "RELAY": "Pass along",
  "RIDER": "One who rides",
  "RIDGE": "Narrow hilltop",
  "RIFLE": "Long gun",
  "RIGHT": "Correct; opposite of left",
  "RIGID": "Stiff; inflexible",
  "RINSE": "Wash lightly",
  "RIPEN": "Become ready to eat",
  "RISEN": "Gone up",
  "RIVAL": "Competitor",
  "RIVER": "Flowing water body",
  "ROBIN": "Red-breasted bird",
  "ROCKY": "Full of stones",
  "ROGUE": "Dishonest person",
  "ROOST": "Bird's resting place",
  "ROUND": "Circular shape",
  "ROUTE": "Travel path",
  "ROYAL": "Of a king or queen",
  "RUMOR": "Unverified story",
  "RURAL": "Countryside",
  "SADLY": "With sorrow",
  "SAINT": "Holy person",
  "SALAD": "Green dish",
  "SCALE": "Measuring tool; fish skin",
  "SCARE": "Frighten",
  "SCENE": "Setting; dramatic moment",
  "SCENT": "Smell; fragrance",
  "SCOPE": "Range; extent",
  "SCORE": "Game points",
  "SCOUT": "Explorer; searcher",
  "SERVE": "Help; dish out",
  "SHADE": "Shadow; tint",
  "SHAFT": "Long pole; mine tunnel",
  "SHALL": "Will; must",
  "SHAME": "Disgrace; guilt",
  "SHAPE": "Form; outline",
  "SHARE": "Divide; portion",
  "SHARK": "Ocean predator",
  "SHARP": "Pointy; keen",
  "SHAWL": "Shoulder wrap",
  "SHEAR": "Cut; clip",
  "SHEEN": "Glossy shine",
  "SHEEP": "Wool animal",
  "SHEER": "Pure; steep",
  "SHELF": "Storage ledge",
  "SHELL": "Hard outer cover",
  "SHIFT": "Move; work period",
  "SHINE": "Give off light",
  "SHORE": "Waterfront",
  "SHORT": "Not long",
  "SHOUT": "Yell; cry out",
  "SIGHT": "Vision; view",
  "SINCE": "From that time",
  "SKATE": "Glide on ice",
  "SKILL": "Ability; talent",
  "SKULL": "Head bone",
  "SLATE": "Writing board; stone",
  "SLAVE": "Forced worker",
  "SLEEP": "Rest; slumber",
  "SLICE": "Cut piece",
  "SLIDE": "Playground equipment",
  "SLOPE": "Incline; hillside",
  "SMALL": "Little; tiny",
  "SMART": "Intelligent; clever",
  "SMELL": "Nose sense",
  "SMILE": "Happy expression",
  "SMOKE": "Fire output",
  "SNAIL": "Slow shell creature",
  "SNAKE": "Slithering reptile",
  "SOLAR": "Of the sun",
  "SOLID": "Not liquid; firm",
  "SOLVE": "Find the answer",
  "SOUND": "Noise; healthy",
  "SOUTH": "Compass direction",
  "SPACE": "Room; outer cosmos",
  "SPARE": "Extra; leftover",
  "SPARK": "Tiny fire bit",
  "SPEAK": "Talk; say",
  "SPEED": "Rate of movement",
  "SPELL": "Cast magic; word letters",
  "SPEND": "Use money",
  "SPICE": "Food seasoning",
  "SPILL": "Overflow; drop",
  "SPINE": "Backbone",
  "SPOKE": "Past of 'speak'; wheel part",
  "SPOON": "Eating utensil",
  "SPORT": "Athletic game",
  "SPRAY": "Mist; scatter",
  "STACK": "Ordered pile",
  "STAFF": "Workers; walking stick",
  "STAGE": "Performance area",
  "STAIN": "Discoloration",
  "STAIR": "Step; staircase",
  "STAKE": "Pointed post; risk",
  "STALE": "Not fresh",
  "STALL": "Delay; booth",
  "STAMP": "Postal mark",
  "STAND": "Be upright",
  "STARE": "Look fixedly",
  "START": "Begin; commence",
  "STATE": "Condition; region",
  "STAVE": "Ward off; barrel strip",
  "STEAD": "Place; substitute",
  "STEAK": "Cut of beef",
  "STEAL": "Take illegally",
  "STEAM": "Water vapor",
  "STEEL": "Strong metal",
  "STEEP": "Very inclined",
  "STEER": "Guide; direct",
  "STERN": "Strict; ship back",
  "STICK": "Wooden rod",
  "STIFF": "Not flexible",
  "STILL": "Motionless; yet",
  "STING": "Bee attack",
  "STOCK": "Supply; shares",
  "STOKE": "Feed a fire",
  "STOLE": "Past of 'steal'; wrap",
  "STONE": "Rock; pebble",
  "STOOD": "Was standing",
  "STOOL": "Backless seat",
  "STORE": "Shop; keep",
  "STORM": "Severe weather",
  "STORY": "Narrative; tale",
  "STOUT": "Solidly built",
  "STOVE": "Cooking appliance",
  "STRAW": "Dried grass stem",
  "STRAY": "Wander off course",
  "STRIP": "Narrow band",
  "STRUM": "Play guitar casually",
  "STUCK": "Unable to move",
  "STUDY": "Learn; office room",
  "STUMP": "Tree remnant",
  "STYLE": "Fashion; manner",
  "SUGAR": "Sweet crystal",
  "SURGE": "Sudden increase",
  "SWAMP": "Wetland; marsh",
  "SWEAR": "Promise; curse",
  "SWEEP": "Clean floor",
  "SWEET": "Sugary taste",
  "SWEPT": "Past of 'sweep'",
  "SWIFT": "Very fast",
  "SWORD": "Bladed weapon",
  "SWORE": "Past of 'swear'",
  "SWUNG": "Past of 'swing'",
  "TABLE": "Flat furniture",
  "TAKEN": "Past of 'take'",
  "TASTE": "Flavor; try food",
  "TEACH": "Instruct; educate",
  "TEARS": "Eye drops; rips",
  "TEMPO": "Musical speed",
  "THICK": "Not thin",
  "THIEF": "Robber; stealer",
  "THING": "Object; item",
  "THINK": "Use the mind",
  "THORN": "Rose prickle",
  "THREE": "Number after two",
  "THROW": "Toss; hurl",
  "THUMB": "Short finger",
  "TIDAL": "Of the tides",
  "TIGER": "Striped big cat",
  "TIGHT": "Not loose",
  "TIMER": "Countdown device",
  "TIRED": "Needing rest",
  "TITLE": "Name; heading",
  "TOAST": "Browned bread",
  "TODAY": "This current day",
  "TOKEN": "Symbol; game piece",
  "TOTAL": "Complete sum",
  "TOUCH": "Feel; make contact",
  "TOUGH": "Strong; difficult",
  "TOWER": "Tall structure",
  "TOXIC": "Poisonous",
  "TRACE": "Follow; small amount",
  "TRACK": "Path; follow",
  "TRADE": "Exchange; commerce",
  "TRAIL": "Hiking path",
  "TRAIN": "Railroad vehicle; practice",
  "TRAIT": "Personal quality",
  "TREAT": "Special reward",
  "TREND": "Popular direction",
  "TRIAL": "Legal hearing; test",
  "TRIBE": "Social group",
  "TRICK": "Clever stunt",
  "TRIED": "Attempted",
  "TROUT": "Freshwater fish",
  "TRULY": "Genuinely; really",
  "TRUNK": "Tree stem; car back",
  "TRUST": "Have faith in",
  "TRUTH": "Factual reality",
  "TWIST": "Turn; bend",
  "ULTRA": "Extremely; beyond",
  "UNDER": "Below; beneath",
  "UNION": "Workers' group",
  "UNITE": "Join together",
  "UNITY": "Togetherness",
  "UNTIL": "Up to the time",
  "UPPER": "Higher part",
  "URBAN": "City-related",
  "USAGE": "How something is used",
  "UTTER": "Complete; speak",
  "VALID": "Legally sound",
  "VALUE": "Worth; importance",
  "VAPOR": "Steam; mist",
  "VAULT": "Safe room; jump over",
  "VERSE": "Poetry line; stanza",
  "VIGOR": "Energetic strength",
  "VINYL": "Record material",
  "VIOLA": "Stringed instrument",
  "VIPER": "Venomous snake",
  "VISIT": "Go see; call on",
  "VITAL": "Essential; crucial",
  "VIVID": "Bright; intense",
  "VOCAL": "Using the voice",
  "VOICE": "Speaking sound",
  "VOTER": "One who casts a ballot",
  "VOUCH": "Guarantee; attest",
  "WAFER": "Thin crisp cookie",
  "WAGON": "Four-wheeled cart",
  "WASTE": "Throw away; garbage",
  "WATCH": "Observe; timepiece",
  "WATER": "H2O liquid",
  "WEARY": "Very tired",
  "WEAVE": "Interlace threads",
  "WEDGE": "Triangular block",
  "WHEAT": "Bread grain",
  "WHEEL": "Circular roller",
  "WHERE": "At what place?",
  "WHICH": "What one?",
  "WHILE": "During the time",
  "WHITE": "Lightest color",
  "WHOLE": "Complete; entire",
  "WHOSE": "Belonging to whom?",
  "WIDOW": "Wife of deceased",
  "WIDTH": "Side-to-side measure",
  "WITCH": "Magical woman",
  "WOMEN": "Adult females",
  "WORLD": "The earth; globe",
  "WORSE": "More bad",
  "WORST": "Most bad",
  "WORTH": "Value; merit",
  "WOULD": "Past tense of 'will'",
  "WOUND": "Injury; wrapped",
  "WRATH": "Fierce anger",
  "WROTE": "Past of 'write'",
  "YOUNG": "Not old; youthful",
  "YOUTH": "Young years",
  "ZEBRA": "Striped animal",
  // 6+ letters
  "BANTER": "Playful conversation",
  "BRIDGE": "Span over water",
  "CHANGE": "Make different",
  "DANGER": "Risk of harm",
  "DIGEST": "Process food; summary",
  "ESTATE": "Large property",
  "FABRIC": "Woven cloth material",
  "GARDEN": "Plant growing area",
  "HONEST": "Truthful; sincere",
  "ISLAND": "Land surrounded by water",
  "JIGSAW": "Puzzle type",
  "KINDLE": "Light a fire; inspire",
  "LADDER": "Climbing device",
  "MODERN": "Contemporary; current",
  "NATURE": "Natural world",
  "ORACLE": "Prophet; wise one",
  "PALACE": "Royal residence",
  "RANGER": "Park guardian",
  "SPIRIT": "Soul; ghost",
  "TRAVEL": "Go on a journey",
  "UNIQUE": "One of a kind"
};

function analyze(def) {
  const grid = def.rows.map(r => r.split(''));
  const rows = grid.length;
  const cols = grid[0].length;

  const isBlack = (r, c) => r < 0 || r >= rows || c < 0 || c >= cols || grid[r][c] === '#';
  const isWhite = (r, c) => r >= 0 && r < rows && c >= 0 && c < cols && grid[r][c] !== '#';

  let num = 0;
  const across = [];
  const down = [];

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      if (isBlack(r, c)) continue;
      const startsAcross = isBlack(r, c - 1) && isWhite(r, c + 1);
      const startsDown = isBlack(r - 1, c) && isWhite(r + 1, c);
      if (startsAcross || startsDown) {
        num++;
        if (startsAcross) {
          let answer = '';
          let cc = c;
          while (cc < cols && grid[r][cc] !== '#') { answer += grid[r][cc]; cc++; }
          const clue = clueBank[answer] || `[MISSING: ${answer}]`;
          across.push({ number: num, clue, answer, row: r, col: c, length: answer.length });
        }
        if (startsDown) {
          let answer = '';
          let rr = r;
          while (rr < rows && grid[rr][c] !== '#') { answer += grid[rr][c]; rr++; }
          const clue = clueBank[answer] || `[MISSING: ${answer}]`;
          down.push({ number: num, clue, answer, row: r, col: c, length: answer.length });
        }
      }
    }
  }

  return { id: def.id, title: def.title, difficulty: def.difficulty, size: Math.max(rows, cols), grid, clues: { across, down } };
}

// Output as puzzles.js content
const results = puzzleDefs.map(analyze);

// Check for missing clues
let hasMissing = false;
for (const r of results) {
  for (const dir of ['across', 'down']) {
    for (const c of r.clues[dir]) {
      if (c.clue.startsWith('[MISSING')) {
        console.error(`Puzzle ${r.id} ${dir} #${c.number}: ${c.clue}`);
        hasMissing = true;
      }
    }
  }
}

if (hasMissing) {
  console.error('\nFix missing clues before generating output.');
  process.exit(1);
}

// Generate output
let out = `/**
 * Crossword Puzzle Data - 10 puzzles
 * Auto-generated and validated. Each grid is internally consistent.
 */
window.Puzzles = [\n`;

for (const r of results) {
  out += `  {\n`;
  out += `    id: ${r.id}, title: ${JSON.stringify(r.title)}, difficulty: ${JSON.stringify(r.difficulty)}, size: ${r.size},\n`;
  out += `    grid: [\n`;
  for (const row of r.grid) {
    out += `      ${JSON.stringify(row)},\n`;
  }
  out += `    ],\n`;
  out += `    clues: {\n`;
  out += `      across: [\n`;
  for (const c of r.clues.across) {
    out += `        { number: ${c.number}, clue: ${JSON.stringify(c.clue)}, answer: ${JSON.stringify(c.answer)}, row: ${c.row}, col: ${c.col}, length: ${c.length} },\n`;
  }
  out += `      ],\n`;
  out += `      down: [\n`;
  for (const c of r.clues.down) {
    out += `        { number: ${c.number}, clue: ${JSON.stringify(c.clue)}, answer: ${JSON.stringify(c.answer)}, row: ${c.row}, col: ${c.col}, length: ${c.length} },\n`;
  }
  out += `      ]\n`;
  out += `    }\n`;
  out += `  },\n`;
}

out += `];\n`;

// Write to file
const fs = require('fs');
fs.writeFileSync(__dirname + '/puzzles.js', out);
console.log(`Generated puzzles.js with ${results.length} puzzles.`);
