/**
 * Trivia Arena Question Bank
 * Each category has 50+ questions
 * Format: { q: "question", a: ["optionA","optionB","optionC","optionD"], c: correctIndex }
 */
window.TriviaQuestions = {

  tech: {
    name: "Technology",
    icon: "\u2699",
    color: "#00d4ff",
    questions: [
      { q: "What does HTML stand for?", a: ["Hyper Text Markup Language","High Tech Modern Language","Hyper Transfer Markup Language","Home Tool Markup Language"], c: 0 },
      { q: "Which company created JavaScript?", a: ["Microsoft","Netscape","Google","Apple"], c: 1 },
      { q: "What year was the first iPhone released?", a: ["2005","2006","2007","2008"], c: 2 },
      { q: "What does CPU stand for?", a: ["Central Process Unit","Central Processing Unit","Computer Personal Unit","Central Program Utility"], c: 1 },
      { q: "Which programming language is known as the 'language of the web'?", a: ["Python","Java","JavaScript","C++"], c: 2 },
      { q: "What does 'HTTP' stand for?", a: ["HyperText Transfer Protocol","High Tech Transfer Protocol","Hyper Transfer Text Protocol","HyperText Transit Protocol"], c: 0 },
      { q: "Who founded Microsoft?", a: ["Steve Jobs","Bill Gates & Paul Allen","Mark Zuckerberg","Larry Page"], c: 1 },
      { q: "What does RAM stand for?", a: ["Read Access Memory","Random Access Memory","Rapid Access Module","Random Allocation Memory"], c: 1 },
      { q: "Which company developed the Android operating system?", a: ["Apple","Microsoft","Google","Samsung"], c: 2 },
      { q: "What is the main language used for iOS app development?", a: ["Java","Kotlin","Swift","C#"], c: 2 },
      { q: "What does GPU stand for?", a: ["General Processing Unit","Graphics Processing Unit","Global Power Unit","Graphics Program Utility"], c: 1 },
      { q: "Who created Linux?", a: ["Dennis Ritchie","Richard Stallman","Linus Torvalds","Ken Thompson"], c: 2 },
      { q: "What year was Google founded?", a: ["1996","1997","1998","1999"], c: 2 },
      { q: "What does USB stand for?", a: ["Universal Serial Bus","United System Bus","Universal System Bridge","Ultra Speed Bus"], c: 0 },
      { q: "Which company created the first commercial microprocessor?", a: ["AMD","Intel","IBM","Texas Instruments"], c: 1 },
      { q: "What does API stand for?", a: ["Applied Programming Interface","Application Program Integration","Application Programming Interface","Automated Process Integration"], c: 2 },
      { q: "What is the name of Apple's virtual assistant?", a: ["Alexa","Cortana","Siri","Bixby"], c: 2 },
      { q: "What does SSD stand for?", a: ["Solid State Drive","Super Speed Disk","System Storage Device","Solid System Drive"], c: 0 },
      { q: "Which language was originally called 'Oak'?", a: ["JavaScript","Java","Python","C#"], c: 1 },
      { q: "What year was Wikipedia launched?", a: ["1999","2000","2001","2002"], c: 2 },
      { q: "What does DNS stand for?", a: ["Digital Network System","Domain Name System","Data Network Service","Dynamic Name Server"], c: 1 },
      { q: "Who is considered the father of computer science?", a: ["John von Neumann","Alan Turing","Charles Babbage","Ada Lovelace"], c: 1 },
      { q: "What does CSS stand for?", a: ["Creative Style Sheets","Cascading Style Sheets","Computer Style System","Coded Style Syntax"], c: 1 },
      { q: "What is the most popular version control system?", a: ["SVN","Mercurial","Git","CVS"], c: 2 },
      { q: "Which company acquired GitHub in 2018?", a: ["Google","Amazon","Microsoft","Facebook"], c: 2 },
      { q: "What does IoT stand for?", a: ["Internet of Things","Integration of Technology","Internet of Technology","Intranet of Things"], c: 0 },
      { q: "What is the name of Amazon's cloud platform?", a: ["Azure","Google Cloud","AWS","DigitalOcean"], c: 2 },
      { q: "What year did Bitcoin launch?", a: ["2007","2008","2009","2010"], c: 2 },
      { q: "What does SQL stand for?", a: ["Structured Query Language","Simple Question Language","System Query Logic","Standard Query Language"], c: 0 },
      { q: "Which company created React?", a: ["Google","Microsoft","Facebook","Netflix"], c: 2 },
      { q: "What does LAN stand for?", a: ["Large Area Network","Local Access Network","Local Area Network","Linked Area Network"], c: 2 },
      { q: "Who invented the World Wide Web?", a: ["Vint Cerf","Tim Berners-Lee","Marc Andreessen","Robert Cailliau"], c: 1 },
      { q: "What does BIOS stand for?", a: ["Basic Input/Output System","Binary Input/Output Software","Basic Integrated Operating System","Built-In Operating System"], c: 0 },
      { q: "What was the first widely used web browser?", a: ["Internet Explorer","Firefox","Mosaic","Netscape Navigator"], c: 2 },
      { q: "What does VPN stand for?", a: ["Virtual Private Network","Very Private Network","Virtual Process Node","Virtual Public Network"], c: 0 },
      { q: "Which language is most associated with data science?", a: ["Java","C++","Python","Ruby"], c: 2 },
      { q: "What year was Spotify launched?", a: ["2006","2008","2010","2012"], c: 1 },
      { q: "What does NFC stand for?", a: ["Near Field Communication","Network Function Controller","New Frequency Channel","National Frequency Communication"], c: 0 },
      { q: "Who co-founded Apple with Steve Jobs?", a: ["Bill Gates","Steve Wozniak","Tim Cook","Jony Ive"], c: 1 },
      { q: "What does HDMI stand for?", a: ["High Definition Media Interface","High Definition Multimedia Interface","Hyper Digital Media Interface","High Display Multimedia Input"], c: 1 },
      { q: "What is the maximum value of a byte?", a: ["128","255","256","512"], c: 1 },
      { q: "Which company created TypeScript?", a: ["Google","Facebook","Microsoft","Oracle"], c: 2 },
      { q: "What does SMTP stand for?", a: ["Simple Mail Transfer Protocol","Secure Mail Transfer Protocol","System Mail Transfer Process","Standard Mail Transit Protocol"], c: 0 },
      { q: "What year was the first email sent?", a: ["1965","1969","1971","1975"], c: 2 },
      { q: "What does URL stand for?", a: ["Universal Resource Locator","Uniform Resource Locator","Unified Resource Link","Universal Reference Locator"], c: 1 },
      { q: "Which company makes the PlayStation?", a: ["Nintendo","Microsoft","Sony","Sega"], c: 2 },
      { q: "What is Moore's Law about?", a: ["Internet speed doubling","Transistor count doubling roughly every 2 years","Hard drive capacity doubling","Software complexity doubling"], c: 1 },
      { q: "What does WiFi stand for?", a: ["Wireless Fidelity","Wireless Frequency","Wide Field Internet","It's a brand name, not an acronym"], c: 3 },
      { q: "Which protocol is used for secure web browsing?", a: ["HTTP","FTP","HTTPS","SMTP"], c: 2 },
      { q: "What is the primary language of Android app development?", a: ["Swift","Kotlin","Dart","C#"], c: 1 },
      { q: "What year was Netflix founded?", a: ["1995","1997","1999","2001"], c: 1 },
      { q: "What does PDF stand for?", a: ["Portable Document Format","Printed Document File","Personal Data File","Public Document Format"], c: 0 }
    ]
  },

  history: {
    name: "History",
    icon: "\u{1F3DB}",
    color: "#f0c84d",
    questions: [
      { q: "In what year did World War II end?", a: ["1943","1944","1945","1946"], c: 2 },
      { q: "Who was the first President of the United States?", a: ["Thomas Jefferson","John Adams","Benjamin Franklin","George Washington"], c: 3 },
      { q: "The Great Wall of China was primarily built to protect against invasions from which direction?", a: ["South","East","West","North"], c: 3 },
      { q: "Which ancient civilization built the Machu Picchu complex?", a: ["Aztec","Maya","Inca","Olmec"], c: 2 },
      { q: "In what year did the Berlin Wall fall?", a: ["1987","1988","1989","1990"], c: 2 },
      { q: "Who was the first woman to fly solo across the Atlantic?", a: ["Bessie Coleman","Amelia Earhart","Harriet Quimby","Jacqueline Cochran"], c: 1 },
      { q: "The French Revolution began in which year?", a: ["1776","1789","1799","1804"], c: 1 },
      { q: "Who wrote the Communist Manifesto with Friedrich Engels?", a: ["Vladimir Lenin","Leon Trotsky","Karl Marx","Joseph Stalin"], c: 2 },
      { q: "What was the name of the ship on which the Pilgrims sailed to America?", a: ["Santa Maria","Mayflower","Endeavour","Victoria"], c: 1 },
      { q: "Which empire was ruled by Genghis Khan?", a: ["Ottoman Empire","Roman Empire","Mongol Empire","Persian Empire"], c: 2 },
      { q: "In what year did the Titanic sink?", a: ["1910","1911","1912","1913"], c: 2 },
      { q: "Who was the Egyptian queen known for her relationships with Julius Caesar and Mark Antony?", a: ["Nefertiti","Hatshepsut","Cleopatra","Isis"], c: 2 },
      { q: "The Renaissance began in which country?", a: ["France","England","Spain","Italy"], c: 3 },
      { q: "Who painted the ceiling of the Sistine Chapel?", a: ["Leonardo da Vinci","Raphael","Michelangelo","Donatello"], c: 2 },
      { q: "What year did the American Civil War begin?", a: ["1859","1860","1861","1862"], c: 2 },
      { q: "Which treaty ended World War I?", a: ["Treaty of Paris","Treaty of Versailles","Treaty of Ghent","Treaty of Westphalia"], c: 1 },
      { q: "Who discovered America in 1492?", a: ["Amerigo Vespucci","Ferdinand Magellan","Christopher Columbus","Leif Erikson"], c: 2 },
      { q: "The Magna Carta was signed in which year?", a: ["1066","1215","1348","1453"], c: 1 },
      { q: "Who was the first man to walk on the Moon?", a: ["Buzz Aldrin","Neil Armstrong","John Glenn","Yuri Gagarin"], c: 1 },
      { q: "Which war was fought between 1950 and 1953?", a: ["Vietnam War","Korean War","Gulf War","Falklands War"], c: 1 },
      { q: "What ancient wonder was located in Alexandria, Egypt?", a: ["Colossus of Rhodes","Hanging Gardens","Lighthouse of Alexandria","Temple of Artemis"], c: 2 },
      { q: "Who was the leader of the Soviet Union during WWII?", a: ["Lenin","Khrushchev","Stalin","Brezhnev"], c: 2 },
      { q: "The Hundred Years' War was primarily between which two countries?", a: ["Spain and Portugal","France and England","Germany and Austria","Italy and Greece"], c: 1 },
      { q: "Who was the first Emperor of Rome?", a: ["Julius Caesar","Augustus","Nero","Caligula"], c: 1 },
      { q: "In what year was the Declaration of Independence signed?", a: ["1774","1775","1776","1777"], c: 2 },
      { q: "Which civilization invented paper?", a: ["Egyptian","Greek","Roman","Chinese"], c: 3 },
      { q: "Who led the Indian independence movement with nonviolent civil disobedience?", a: ["Jawaharlal Nehru","Subhas Chandra Bose","Mahatma Gandhi","B.R. Ambedkar"], c: 2 },
      { q: "The Black Death swept through Europe in which century?", a: ["12th century","13th century","14th century","15th century"], c: 2 },
      { q: "Who was assassinated on the Ides of March, 44 BC?", a: ["Augustus","Brutus","Julius Caesar","Mark Antony"], c: 2 },
      { q: "What year did the Soviet Union dissolve?", a: ["1989","1990","1991","1992"], c: 2 },
      { q: "Which country was NOT part of the Allied Powers in WWII?", a: ["United Kingdom","France","Italy","United States"], c: 2 },
      { q: "The Rosetta Stone helped decipher which ancient script?", a: ["Cuneiform","Egyptian hieroglyphs","Linear A","Sanskrit"], c: 1 },
      { q: "Who was the first female Prime Minister of the United Kingdom?", a: ["Theresa May","Queen Victoria","Margaret Thatcher","Elizabeth I"], c: 2 },
      { q: "The Industrial Revolution began in which country?", a: ["France","Germany","United States","Great Britain"], c: 3 },
      { q: "What was the name of the Allied invasion of Normandy?", a: ["Operation Market Garden","Operation Barbarossa","Operation Overlord","Operation Torch"], c: 2 },
      { q: "Who was the last Pharaoh of Ancient Egypt?", a: ["Ramses II","Tutankhamun","Cleopatra VII","Hatshepsut"], c: 2 },
      { q: "The Silk Road connected China to which region?", a: ["Sub-Saharan Africa","South America","Mediterranean/Europe","Australia"], c: 2 },
      { q: "In which year did Japan attack Pearl Harbor?", a: ["1939","1940","1941","1942"], c: 2 },
      { q: "Who wrote 'The Art of War'?", a: ["Confucius","Sun Tzu","Lao Tzu","Kublai Khan"], c: 1 },
      { q: "Which revolution began in 1917?", a: ["French Revolution","American Revolution","Russian Revolution","Chinese Revolution"], c: 2 },
      { q: "The ancient city of Pompeii was destroyed by which volcano?", a: ["Mount Etna","Mount Olympus","Mount Vesuvius","Mount Fuji"], c: 2 },
      { q: "Who was the British monarch during the American Revolution?", a: ["George II","George III","George IV","Victoria"], c: 1 },
      { q: "The Partition of India occurred in which year?", a: ["1945","1946","1947","1948"], c: 2 },
      { q: "Which country gifted the Statue of Liberty to the United States?", a: ["England","Spain","France","Italy"], c: 2 },
      { q: "What was the longest-lasting empire in history?", a: ["British Empire","Roman Empire","Ottoman Empire","Byzantine Empire"], c: 2 },
      { q: "Who was the famous nurse during the Crimean War?", a: ["Clara Barton","Mary Seacole","Florence Nightingale","Dorothea Dix"], c: 2 },
      { q: "The Aztec Empire was located in modern-day which country?", a: ["Peru","Colombia","Mexico","Guatemala"], c: 2 },
      { q: "Who invented the printing press?", a: ["Benjamin Franklin","Johannes Gutenberg","William Caxton","Bi Sheng"], c: 1 },
      { q: "The Cold War was primarily between which two superpowers?", a: ["USA and China","USA and USSR","UK and USSR","USA and Germany"], c: 1 },
      { q: "In what year did apartheid officially end in South Africa?", a: ["1990","1991","1993","1994"], c: 3 },
      { q: "Who was the first explorer to circumnavigate the globe?", a: ["Christopher Columbus","Vasco da Gama","Ferdinand Magellan's expedition","Francis Drake"], c: 2 },
      { q: "The Battle of Waterloo took place in which year?", a: ["1805","1812","1815","1820"], c: 2 }
    ]
  },

  science: {
    name: "Science",
    icon: "\u{1F52C}",
    color: "#39ff14",
    questions: [
      { q: "What is the chemical symbol for gold?", a: ["Go","Gd","Au","Ag"], c: 2 },
      { q: "How many bones are in the adult human body?", a: ["186","206","216","256"], c: 1 },
      { q: "What planet is known as the Red Planet?", a: ["Venus","Jupiter","Mars","Saturn"], c: 2 },
      { q: "What is the speed of light in a vacuum (approximately)?", a: ["300,000 km/s","150,000 km/s","500,000 km/s","1,000,000 km/s"], c: 0 },
      { q: "What is the most abundant gas in Earth's atmosphere?", a: ["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"], c: 2 },
      { q: "What is the powerhouse of the cell?", a: ["Nucleus","Ribosome","Mitochondria","Golgi apparatus"], c: 2 },
      { q: "What is the hardest natural substance on Earth?", a: ["Titanium","Diamond","Quartz","Tungsten"], c: 1 },
      { q: "How many chromosomes do humans have?", a: ["23","44","46","48"], c: 2 },
      { q: "What is the largest organ in the human body?", a: ["Liver","Brain","Skin","Lungs"], c: 2 },
      { q: "What gas do plants primarily absorb from the atmosphere?", a: ["Oxygen","Nitrogen","Carbon Dioxide","Methane"], c: 2 },
      { q: "What is the atomic number of carbon?", a: ["4","6","8","12"], c: 1 },
      { q: "Which planet has the most moons?", a: ["Jupiter","Saturn","Uranus","Neptune"], c: 1 },
      { q: "What is the chemical formula for table salt?", a: ["NaO","NaCl","KCl","CaCl2"], c: 1 },
      { q: "How long does it take light from the Sun to reach Earth?", a: ["4 minutes","6 minutes","8 minutes","12 minutes"], c: 2 },
      { q: "What is the smallest unit of matter?", a: ["Molecule","Atom","Proton","Quark"], c: 3 },
      { q: "What type of animal is a dolphin?", a: ["Fish","Reptile","Mammal","Amphibian"], c: 2 },
      { q: "What is absolute zero in Celsius?", a: ["-100 C","-200 C","-273.15 C","-373.15 C"], c: 2 },
      { q: "Which element has the chemical symbol Fe?", a: ["Fluorine","Francium","Iron","Fermium"], c: 2 },
      { q: "What is the closest star to Earth (besides the Sun)?", a: ["Sirius","Alpha Centauri","Betelgeuse","Proxima Centauri"], c: 3 },
      { q: "How many elements are in the periodic table (as of 2024)?", a: ["108","112","118","124"], c: 2 },
      { q: "What is the pH of pure water?", a: ["5","6","7","8"], c: 2 },
      { q: "Which blood type is the universal donor?", a: ["A","B","AB","O negative"], c: 3 },
      { q: "What force keeps planets in orbit around the Sun?", a: ["Magnetic force","Nuclear force","Gravity","Centripetal force"], c: 2 },
      { q: "What is the largest planet in our solar system?", a: ["Saturn","Neptune","Jupiter","Uranus"], c: 2 },
      { q: "DNA stands for what?", a: ["Deoxyribonucleic Acid","Dinitrogen Acid","Dynamic Nuclear Acid","Dual Nucleotide Arrangement"], c: 0 },
      { q: "What is the boiling point of water at sea level in Fahrenheit?", a: ["180 F","200 F","212 F","220 F"], c: 2 },
      { q: "Which vitamin is produced when the skin is exposed to sunlight?", a: ["Vitamin A","Vitamin B","Vitamin C","Vitamin D"], c: 3 },
      { q: "What is the study of earthquakes called?", a: ["Geology","Seismology","Volcanology","Tectonics"], c: 1 },
      { q: "How many planets are in our solar system?", a: ["7","8","9","10"], c: 1 },
      { q: "What particle has a positive charge?", a: ["Electron","Neutron","Proton","Photon"], c: 2 },
      { q: "What is the largest species of shark?", a: ["Great White","Hammerhead","Whale Shark","Megalodon"], c: 2 },
      { q: "What is Newton's first law of motion about?", a: ["Force and acceleration","Inertia","Action and reaction","Gravity"], c: 1 },
      { q: "Which organ filters blood in the human body?", a: ["Heart","Liver","Kidney","Spleen"], c: 2 },
      { q: "What type of rock is formed from cooled lava?", a: ["Sedimentary","Metamorphic","Igneous","Limestone"], c: 2 },
      { q: "What is the chemical formula for water?", a: ["HO","H2O","H2O2","OH"], c: 1 },
      { q: "What is the Milky Way?", a: ["A constellation","A nebula","A galaxy","A star cluster"], c: 2 },
      { q: "Which gas is essential for human respiration?", a: ["Nitrogen","Carbon Dioxide","Oxygen","Hydrogen"], c: 2 },
      { q: "How many chambers does the human heart have?", a: ["2","3","4","5"], c: 2 },
      { q: "What is the speed of sound in air (approximately)?", a: ["100 m/s","343 m/s","500 m/s","767 m/s"], c: 1 },
      { q: "What is the study of fungi called?", a: ["Botany","Mycology","Zoology","Ecology"], c: 1 },
      { q: "Which planet is known for its prominent ring system?", a: ["Jupiter","Neptune","Uranus","Saturn"], c: 3 },
      { q: "What is the most common element in the universe?", a: ["Helium","Oxygen","Carbon","Hydrogen"], c: 3 },
      { q: "What is the name for a group of stars forming a pattern?", a: ["Galaxy","Nebula","Constellation","Star cluster"], c: 2 },
      { q: "What is the main function of red blood cells?", a: ["Fight infection","Carry oxygen","Clot blood","Produce antibodies"], c: 1 },
      { q: "Which scientist developed the theory of general relativity?", a: ["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"], c: 2 },
      { q: "What is the chemical symbol for sodium?", a: ["So","Sd","Na","No"], c: 2 },
      { q: "What phenomenon causes a rainbow?", a: ["Reflection only","Refraction and dispersion of light","Diffraction","Polarization"], c: 1 },
      { q: "What is the tallest type of grass?", a: ["Sugarcane","Corn","Bamboo","Wheat"], c: 2 },
      { q: "How many teeth does an adult human typically have?", a: ["28","30","32","34"], c: 2 },
      { q: "What is the densest planet in our solar system?", a: ["Jupiter","Mars","Earth","Mercury"], c: 2 },
      { q: "Which part of the brain controls balance?", a: ["Cerebrum","Cerebellum","Brain stem","Hypothalamus"], c: 1 },
      { q: "What is the process by which plants make food using sunlight?", a: ["Respiration","Fermentation","Photosynthesis","Transpiration"], c: 2 }
    ]
  },

  popculture: {
    name: "Pop Culture",
    icon: "\u{1F3AC}",
    color: "#ff2d7b",
    questions: [
      { q: "Which movie features the quote 'May the Force be with you'?", a: ["Star Trek","The Matrix","Star Wars","Guardians of the Galaxy"], c: 2 },
      { q: "What is the name of the fictional country in 'Black Panther'?", a: ["Zamunda","Wakanda","Genovia","Latveria"], c: 1 },
      { q: "Who played Jack in 'Titanic' (1997)?", a: ["Brad Pitt","Matt Damon","Leonardo DiCaprio","Johnny Depp"], c: 2 },
      { q: "What band was Freddie Mercury the lead singer of?", a: ["The Beatles","Led Zeppelin","Queen","The Rolling Stones"], c: 2 },
      { q: "In 'Friends', what is the name of Ross's first wife?", a: ["Emily","Rachel","Carol","Julie"], c: 2 },
      { q: "Which superhero is also known as Diana Prince?", a: ["Black Widow","Captain Marvel","Supergirl","Wonder Woman"], c: 3 },
      { q: "What year was the first 'Harry Potter' book published?", a: ["1995","1996","1997","1998"], c: 2 },
      { q: "Who directed 'Jurassic Park'?", a: ["James Cameron","George Lucas","Steven Spielberg","Ridley Scott"], c: 2 },
      { q: "What is the highest-grossing film of all time (adjusted)?", a: ["Avengers: Endgame","Avatar","Titanic","Gone with the Wind"], c: 1 },
      { q: "Which artist released the album 'Thriller'?", a: ["Prince","Madonna","Michael Jackson","Whitney Houston"], c: 2 },
      { q: "In 'The Simpsons', what is Homer's middle name?", a: ["James","Jay","John","Julius"], c: 1 },
      { q: "Which TV show features dragons and the Iron Throne?", a: ["Lord of the Rings","The Witcher","Game of Thrones","Vikings"], c: 2 },
      { q: "Who wrote the 'Lord of the Rings' trilogy?", a: ["C.S. Lewis","George R.R. Martin","J.R.R. Tolkien","Terry Pratchett"], c: 2 },
      { q: "What is the name of Batman's butler?", a: ["Jarvis","Alfred","Watson","Jeeves"], c: 1 },
      { q: "Which Disney movie features the song 'Let It Go'?", a: ["Tangled","Moana","Frozen","Brave"], c: 2 },
      { q: "Who plays Iron Man in the MCU?", a: ["Chris Evans","Chris Hemsworth","Robert Downey Jr.","Mark Ruffalo"], c: 2 },
      { q: "What is the name of the coffee shop in 'Friends'?", a: ["Central Perk","The Brew","Coffee Culture","The Java Hut"], c: 0 },
      { q: "Which band released 'Bohemian Rhapsody'?", a: ["Pink Floyd","Queen","Led Zeppelin","The Who"], c: 1 },
      { q: "In 'Breaking Bad', what is Walter White's alias?", a: ["Saul Goodman","Heisenberg","The Professor","Mr. White"], c: 1 },
      { q: "What fictional school does Harry Potter attend?", a: ["Xavier's School","Hogwarts","Brakebills","Unseen University"], c: 1 },
      { q: "Which pop star is known as the 'Queen of Pop'?", a: ["Lady Gaga","Beyonce","Madonna","Taylor Swift"], c: 2 },
      { q: "What is the name of Sherlock Holmes' companion?", a: ["Inspector Lestrade","Dr. Watson","Mycroft","Mrs. Hudson"], c: 1 },
      { q: "Which animated movie features a fish named Nemo?", a: ["Shark Tale","The Little Mermaid","Finding Nemo","Moana"], c: 2 },
      { q: "Who created Mickey Mouse?", a: ["Chuck Jones","Hanna-Barbera","Walt Disney","Ub Iwerks"], c: 2 },
      { q: "What video game features a plumber named Mario?", a: ["Sonic","Pac-Man","Donkey Kong / Super Mario Bros.","Mega Man"], c: 2 },
      { q: "Which TV series is set in Hawkins, Indiana?", a: ["Stranger Things","Supernatural","The X-Files","Twin Peaks"], c: 0 },
      { q: "Who sang 'Imagine'?", a: ["Paul McCartney","George Harrison","John Lennon","Ringo Starr"], c: 2 },
      { q: "In which movie does a character say 'I'll be back'?", a: ["Robocop","Die Hard","The Terminator","Predator"], c: 2 },
      { q: "What is the name of the wizarding pub in London in Harry Potter?", a: ["The Three Broomsticks","The Leaky Cauldron","The Hog's Head","The Prancing Pony"], c: 1 },
      { q: "Which K-pop group released 'Dynamite'?", a: ["BLACKPINK","EXO","BTS","TWICE"], c: 2 },
      { q: "Who played the Joker in 'The Dark Knight'?", a: ["Jack Nicholson","Joaquin Phoenix","Jared Leto","Heath Ledger"], c: 3 },
      { q: "What is the name of SpongeBob's best friend?", a: ["Squidward","Sandy","Patrick","Gary"], c: 2 },
      { q: "Which movie franchise features 'Hogwarts Express'?", a: ["Percy Jackson","Narnia","Harry Potter","Lord of the Rings"], c: 2 },
      { q: "Who is the author of 'A Song of Ice and Fire' series?", a: ["Brandon Sanderson","George R.R. Martin","Patrick Rothfuss","Robert Jordan"], c: 1 },
      { q: "What Netflix series features a chess prodigy named Beth Harmon?", a: ["Ozark","The Queen's Gambit","Lupin","Bridgerton"], c: 1 },
      { q: "Which rapper's real name is Marshall Mathers?", a: ["Jay-Z","Kanye West","Eminem","Lil Wayne"], c: 2 },
      { q: "In 'The Office' (US), what is the name of the paper company?", a: ["Dunder Mifflin","Wernham Hogg","Initech","Prestige Worldwide"], c: 0 },
      { q: "Who directed 'Inception'?", a: ["David Fincher","Christopher Nolan","Denis Villeneuve","Martin Scorsese"], c: 1 },
      { q: "What is the name of Thor's hammer?", a: ["Stormbreaker","Gungnir","Mjolnir","Excalibur"], c: 2 },
      { q: "Which TV show features characters named Sheldon and Leonard?", a: ["Seinfeld","The Big Bang Theory","How I Met Your Mother","New Girl"], c: 1 },
      { q: "What is the best-selling video game of all time?", a: ["Tetris","GTA V","Minecraft","Wii Sports"], c: 2 },
      { q: "Who played Forrest Gump?", a: ["Robin Williams","Bill Murray","Tom Hanks","Jim Carrey"], c: 2 },
      { q: "Which musician is known for the album 'Purple Rain'?", a: ["David Bowie","Prince","Jimi Hendrix","Elton John"], c: 1 },
      { q: "What is the name of the magical map in Harry Potter?", a: ["Map of Secrets","The Marauder's Map","Dumbledore's Atlas","The Enchanted Chart"], c: 1 },
      { q: "Which animated series features four boys from Colorado?", a: ["Family Guy","The Simpsons","South Park","Bob's Burgers"], c: 2 },
      { q: "Who is known as the 'King of Rock and Roll'?", a: ["Chuck Berry","Little Richard","Elvis Presley","Buddy Holly"], c: 2 },
      { q: "What is Darth Vader's real name?", a: ["Luke Skywalker","Anakin Skywalker","Ben Solo","Palpatine"], c: 1 },
      { q: "Which streaming service produced 'Squid Game'?", a: ["Amazon Prime","Disney+","Netflix","HBO Max"], c: 2 },
      { q: "Who voiced Woody in 'Toy Story'?", a: ["Tim Allen","Robin Williams","Tom Hanks","Billy Crystal"], c: 2 },
      { q: "What is the name of the theme park in 'Jurassic Park'?", a: ["Dino World","Jurassic World","Jurassic Park","Isla Nublar Park"], c: 2 },
      { q: "Which Taylor Swift album was released in 2020?", a: ["Reputation","Lover","Folklore","Midnights"], c: 2 },
      { q: "What is the name of the kingdom in 'Frozen'?", a: ["Corona","Arendelle","Agrabah","DunBroch"], c: 1 }
    ]
  }

};
