import { ComponentCategory } from '@/types/component';
import { Customization, defaultCustomization } from '@/types/customization';

// Text slot definition for inline editing
export type TextSlot = {
  key: string;           // e.g., 'title', 'description', 'buttonText'
  label: string;         // Display name for UI
  defaultValue: string;  // Placeholder text
  multiline?: boolean;   // textarea vs input
};

// Component definition for the registry
export type ComponentDefinition = {
  id: string;
  name: string;
  category: ComponentCategory;
  description: string;
  tags: string[];
  customizableProps: string[];
  defaultCustomization: Partial<Customization>;
  textSlots?: TextSlot[]; // Editable text elements within component
};

// Component Library - All components across categories
export const componentLibrary: Record<ComponentCategory, ComponentDefinition[]> = {
  cards: [
    {
      id: 'glass-card',
      name: 'Glassmorphic Card',
      category: 'cards',
      description: 'Frosted glass effect with customizable blur and transparency',
      tags: ['glass', 'blur', 'modern', 'backdrop'],
      customizableProps: ['glassOpacity', 'blurAmount', 'glassBorderOpacity', 'shadowIntensity'],
      defaultCustomization: {
        ...defaultCustomization,
        glassOpacity: '15',
        glassBorderOpacity: '40',
        blurAmount: '12',
        shadowIntensity: '50',
      },
      textSlots: [
        { key: 'title', label: 'Title', defaultValue: 'Glass Card' },
        { key: 'description', label: 'Description', defaultValue: 'A beautiful frosted glass effect with customizable blur.', multiline: true },
      ],
    },
    {
      id: 'floating-card',
      name: '3D Floating Card',
      category: 'cards',
      description: 'Hover to see 3D lift effect with perspective transforms',
      tags: ['3d', 'hover', 'perspective', 'float'],
      customizableProps: ['glassOpacity', 'blurAmount', 'floatHeight', 'rotationX', 'rotationY', 'duration'],
      defaultCustomization: {
        ...defaultCustomization,
        floatHeight: '10',
        rotationX: '5',
        rotationY: '5',
        duration: '300',
      },
    },
    {
      id: 'neon-card',
      name: 'Neon Glow Card',
      category: 'cards',
      description: 'Pulsing neon glow effect with customizable intensity',
      tags: ['neon', 'glow', 'pulse', 'cyberpunk'],
      customizableProps: ['glassOpacity', 'blurAmount', 'glowIntensity', 'glowSpread', 'pulseSpeed'],
      defaultCustomization: {
        ...defaultCustomization,
        glowIntensity: '60',
        glowSpread: '40',
        pulseSpeed: '2',
      },
    },
    {
      id: 'profile-card',
      name: 'Profile Card',
      category: 'cards',
      description: 'User profile card with avatar, bio, stats, and social links',
      tags: ['profile', 'user', 'avatar', 'social', 'bio'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'avatarSize', 'showSocialLinks'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        glassOpacity: '15',
        avatarSize: '80',
        showSocialLinks: 'true',
      },
      textSlots: [
        { key: 'name', label: 'Name', defaultValue: 'Alex Chen' },
        { key: 'role', label: 'Role', defaultValue: 'Senior Developer' },
        { key: 'bio', label: 'Bio', defaultValue: 'Building the future of web development.', multiline: true },
      ],
    },
    {
      id: 'product-card',
      name: 'Product Card',
      category: 'cards',
      description: 'E-commerce product card with image, price, rating, and add to cart',
      tags: ['product', 'ecommerce', 'shop', 'price', 'rating'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'imageHeight', 'showRating'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        imageHeight: '200',
        showRating: 'true',
      },
      textSlots: [
        { key: 'productName', label: 'Product Name', defaultValue: 'Premium Headphones' },
        { key: 'price', label: 'Price', defaultValue: '$299' },
        { key: 'buttonText', label: 'Button Text', defaultValue: 'Add to Cart' },
      ],
    },
    {
      id: 'blog-card',
      name: 'Blog Card',
      category: 'cards',
      description: 'Blog post preview with image, excerpt, author, and engagement',
      tags: ['blog', 'post', 'article', 'author', 'preview'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'excerptLines', 'showAuthor'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        excerptLines: '3',
        showAuthor: 'true',
      },
      textSlots: [
        { key: 'title', label: 'Title', defaultValue: 'Getting Started with AI' },
        { key: 'excerpt', label: 'Excerpt', defaultValue: 'Learn how to leverage AI tools to boost your productivity and build amazing products.', multiline: true },
        { key: 'author', label: 'Author', defaultValue: 'Sarah Miller' },
      ],
    },
    {
      id: 'pricing-card-alt',
      name: 'Pricing Card Alt',
      category: 'cards',
      description: 'Alternative pricing card with animated border and toggle',
      tags: ['pricing', 'plans', 'subscription', 'features', 'billing'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
      },
    },
    {
      id: 'team-member-card',
      name: 'Team Member Card',
      category: 'cards',
      description: 'Team member card with photo, role, skills, and social links',
      tags: ['team', 'member', 'profile', 'staff', 'employee'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
      },
    },
  ],
  buttons: [
    {
      id: 'gradient-btn',
      name: 'Gradient Button',
      category: 'buttons',
      description: 'Beautiful gradient with smooth hover effects',
      tags: ['gradient', 'colorful', 'hover', 'modern'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'hoverScale', 'shadowIntensity'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        hoverScale: '1.05',
        shadowIntensity: '50',
      },
      textSlots: [
        { key: 'buttonText', label: 'Button Text', defaultValue: 'Get Started' },
      ],
    },
    {
      id: 'neo-btn',
      name: 'Neomorphic Button',
      category: 'buttons',
      description: 'Soft shadow neomorphic design with press states',
      tags: ['neomorphic', 'soft', 'shadow', 'minimal'],
      customizableProps: ['glassOpacity', 'blurAmount', 'neoDepth', 'softShadowIntensity', 'duration'],
      defaultCustomization: {
        ...defaultCustomization,
        neoDepth: '8',
        softShadowIntensity: '20',
        duration: '300',
      },
      textSlots: [
        { key: 'buttonText', label: 'Button Text', defaultValue: 'Press Me' },
      ],
    },
    {
      id: 'particle-btn',
      name: 'Particle Effect Button',
      category: 'buttons',
      description: 'Explosion particle effects on click',
      tags: ['particle', 'explosion', 'animation', 'interactive'],
      customizableProps: ['glassOpacity', 'blurAmount', 'particleCount', 'explosionRadius', 'duration'],
      defaultCustomization: {
        ...defaultCustomization,
        particleCount: '20',
        explosionRadius: '50',
        duration: '300',
      },
    },
    {
      id: 'outline-btn',
      name: 'Outline Button',
      category: 'buttons',
      description: 'Ghost/outline button with hover fill effect',
      tags: ['outline', 'ghost', 'hover', 'minimal', 'border'],
      customizableProps: ['glassOpacity', 'blurAmount', 'hoverScale', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        hoverScale: '1.05',
      },
      textSlots: [
        { key: 'buttonText', label: 'Button Text', defaultValue: 'Learn More' },
      ],
    },
    {
      id: 'icon-btn',
      name: 'Icon Button',
      category: 'buttons',
      description: 'Circular icon-only buttons in multiple variants',
      tags: ['icon', 'circular', 'minimal', 'action', 'round'],
      customizableProps: ['glassOpacity', 'blurAmount', 'hoverScale', 'shadowIntensity', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        hoverScale: '1.1',
        shadowIntensity: '50',
      },
    },
    {
      id: 'split-btn',
      name: 'Split Button',
      category: 'buttons',
      description: 'Button with dropdown arrow for additional actions',
      tags: ['split', 'dropdown', 'menu', 'actions', 'combo'],
      customizableProps: ['glassOpacity', 'blurAmount', 'hoverScale', 'shadowIntensity', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        hoverScale: '1.02',
        shadowIntensity: '50',
      },
    },
    {
      id: 'loading-btn',
      name: 'Loading Button',
      category: 'buttons',
      description: 'Button with loading spinner and success states',
      tags: ['loading', 'spinner', 'async', 'submit', 'progress'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'spinnerSize', 'showSuccessState'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        spinnerSize: '16',
        showSuccessState: 'true',
      },
    },
    {
      id: 'pill-btn',
      name: 'Pill Button',
      category: 'buttons',
      description: 'Rounded pill-shaped buttons with gradient options',
      tags: ['pill', 'rounded', 'gradient', 'tag', 'chip'],
      customizableProps: ['glassOpacity', 'blurAmount', 'hoverScale', 'shadowIntensity', 'gradientAngle'],
      defaultCustomization: {
        ...defaultCustomization,
        hoverScale: '1.05',
        shadowIntensity: '50',
        gradientAngle: '135',
      },
    },
    {
      id: 'animated-border-btn',
      name: 'Animated Border Button',
      category: 'buttons',
      description: 'Buttons with rotating, pulsing, and shimmer gradient borders',
      tags: ['animated', 'border', 'gradient', 'shimmer', 'rainbow'],
      customizableProps: ['glassOpacity', 'blurAmount', 'hoverScale', 'gradientAngle', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        hoverScale: '1.03',
        gradientAngle: '135',
      },
    },
  ],
  badges: [
    {
      id: 'status-badge',
      name: 'Status Badge',
      category: 'badges',
      description: 'Badge with dot indicator for online/offline/away status',
      tags: ['status', 'online', 'offline', 'away', 'indicator', 'dot'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'badgeSize', 'pulseAnimation', 'surfaceColor'],
      defaultCustomization: {
        ...defaultCustomization,
        badgeSize: '24',
        pulseAnimation: 'false',
      },
    },
    {
      id: 'notification-badge',
      name: 'Notification Badge',
      category: 'badges',
      description: 'Badge with count number for notifications and alerts',
      tags: ['notification', 'count', 'number', 'alert', 'bell', 'unread'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'badgeSize', 'pulseAnimation'],
      defaultCustomization: {
        ...defaultCustomization,
        badgeSize: '24',
        pulseAnimation: 'true',
      },
    },
  ],
  forms: [
    {
      id: 'animated-input',
      name: 'Animated Input',
      category: 'forms',
      description: 'Form inputs with staggered entrance and focus animations',
      tags: ['animated', 'input', 'form', 'stagger', 'focus'],
      customizableProps: ['glassOpacity', 'blurAmount', 'duration', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        duration: '300',
        inputHeight: '40',
        focusRingWidth: '2',
      },
    },
    {
      id: 'floating-label-input',
      name: 'Floating Label Input',
      category: 'forms',
      description: 'Material Design inspired inputs with floating labels',
      tags: ['floating', 'label', 'material', 'form', 'input'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        inputHeight: '48',
        focusRingWidth: '2',
      },
    },
    {
      id: 'search-command',
      name: 'Search Command',
      category: 'forms',
      description: 'Command palette style search with keyboard navigation',
      tags: ['search', 'command', 'keyboard', 'palette', 'filter'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        glassOpacity: '15',
        inputHeight: '44',
        focusRingWidth: '2',
      },
    },
    {
      id: 'select-dropdown',
      name: 'Select Dropdown',
      category: 'forms',
      description: 'Custom styled select dropdown with smooth animations',
      tags: ['select', 'dropdown', 'form', 'animated', 'menu'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        inputHeight: '40',
        focusRingWidth: '2',
      },
    },
    {
      id: 'checkbox-group',
      name: 'Checkbox Group',
      category: 'forms',
      description: 'Styled checkbox group with descriptions and animations',
      tags: ['checkbox', 'group', 'form', 'toggle', 'preferences'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        focusRingWidth: '2',
      },
    },
    {
      id: 'radio-group',
      name: 'Radio Group',
      category: 'forms',
      description: 'Card-style radio buttons with smooth selection animation',
      tags: ['radio', 'group', 'form', 'selection', 'cards'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        focusRingWidth: '2',
      },
    },
    {
      id: 'toggle-switch',
      name: 'Toggle Switch',
      category: 'forms',
      description: 'Animated on/off toggle switches with icons',
      tags: ['toggle', 'switch', 'form', 'settings', 'animated'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        focusRingWidth: '2',
      },
    },
    {
      id: 'range-slider',
      name: 'Range Slider',
      category: 'forms',
      description: 'Gradient range slider with value display and glow effects',
      tags: ['slider', 'range', 'form', 'input', 'gradient'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        focusRingWidth: '2',
      },
    },
    {
      id: 'tag-input',
      name: 'Tag Input',
      category: 'forms',
      description: 'Input field that creates removable tags with autocomplete',
      tags: ['tags', 'input', 'form', 'chips', 'autocomplete'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        inputHeight: '40',
        focusRingWidth: '2',
      },
    },
    {
      id: 'password-input',
      name: 'Password Input',
      category: 'forms',
      description: 'Password field with show/hide toggle and strength meter',
      tags: ['password', 'input', 'form', 'security', 'strength'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        inputHeight: '40',
        focusRingWidth: '2',
      },
    },
    {
      id: 'otp-input',
      name: 'OTP Input',
      category: 'forms',
      description: 'One-time password input with auto-focus and verification',
      tags: ['otp', 'verification', 'form', 'auth', 'security'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        inputHeight: '48',
        focusRingWidth: '2',
      },
    },
    {
      id: 'date-picker-input',
      name: 'Date Picker Input',
      category: 'forms',
      description: 'Styled date input with calendar dropdown and quick actions',
      tags: ['date', 'picker', 'calendar', 'form', 'input'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        inputHeight: '40',
        focusRingWidth: '2',
      },
    },
    {
      id: 'file-upload',
      name: 'File Upload',
      category: 'forms',
      description: 'Drag and drop file upload zone with progress indicators',
      tags: ['file', 'upload', 'form', 'dropzone', 'progress'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        focusRingWidth: '2',
      },
    },
    {
      id: 'textarea-autosize',
      name: 'Textarea Autosize',
      category: 'forms',
      description: 'Auto-expanding textarea with toolbar and character counter',
      tags: ['textarea', 'input', 'form', 'autosize', 'message'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        focusRingWidth: '2',
      },
    },
    {
      id: 'form-card',
      name: 'Form Card',
      category: 'forms',
      description: 'Complete form layout with progress tracking and validation',
      tags: ['form', 'card', 'complete', 'validation', 'progress'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'inputHeight', 'focusRingWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        glassOpacity: '15',
        inputHeight: '40',
        focusRingWidth: '2',
      },
    },
  ],
  navigation: [
    {
      id: 'glass-nav',
      name: 'Glass Navigation',
      category: 'navigation',
      description: 'Glassmorphic navigation bar with smooth indicator transitions',
      tags: ['glass', 'navbar', 'blur', 'indicator', 'modern'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'indicatorSize', 'showLabels'],
      defaultCustomization: {
        ...defaultCustomization,
        glassOpacity: '15',
        blurAmount: '12',
        indicatorSize: '4',
        showLabels: 'true',
      },
    },
    {
      id: 'command-palette',
      name: 'Command Palette',
      category: 'navigation',
      description: 'VS Code style command palette with grouped commands',
      tags: ['command', 'palette', 'search', 'keyboard', 'shortcuts'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'indicatorSize', 'showLabels'],
      defaultCustomization: {
        ...defaultCustomization,
        glassOpacity: '15',
        indicatorSize: '4',
        showLabels: 'true',
      },
    },
    {
      id: 'breadcrumb-nav',
      name: 'Breadcrumb Nav',
      category: 'navigation',
      description: 'Breadcrumb trail navigation with animated separators',
      tags: ['breadcrumb', 'trail', 'path', 'navigation', 'hierarchy'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'indicatorSize', 'showLabels'],
      defaultCustomization: {
        ...defaultCustomization,
        indicatorSize: '4',
        showLabels: 'true',
      },
    },
    {
      id: 'tabs-nav',
      name: 'Tabs Navigation',
      category: 'navigation',
      description: 'Horizontal tabs with animated indicator and multiple styles',
      tags: ['tabs', 'navigation', 'indicator', 'animated', 'menu'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'indicatorSize', 'showLabels'],
      defaultCustomization: {
        ...defaultCustomization,
        indicatorSize: '3',
        showLabels: 'true',
      },
    },
    {
      id: 'pagination-nav',
      name: 'Pagination Nav',
      category: 'navigation',
      description: 'Page navigation with numbers, arrows, and compact modes',
      tags: ['pagination', 'pages', 'navigation', 'numbers', 'arrows'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'indicatorSize', 'showLabels'],
      defaultCustomization: {
        ...defaultCustomization,
        indicatorSize: '4',
        showLabels: 'true',
      },
    },
    {
      id: 'sidebar-nav',
      name: 'Sidebar Navigation',
      category: 'navigation',
      description: 'Collapsible sidebar with icons, sections, and user profile',
      tags: ['sidebar', 'menu', 'navigation', 'collapse', 'icons'],
      customizableProps: ['glassOpacity', 'blurAmount', 'sidebarWidth', 'collapseWidth', 'borderRadius', 'indicatorSize', 'showLabels'],
      defaultCustomization: {
        ...defaultCustomization,
        sidebarWidth: '240',
        collapseWidth: '70',
        indicatorSize: '4',
        showLabels: 'true',
      },
    },
    {
      id: 'mobile-menu-nav',
      name: 'Mobile Menu Nav',
      category: 'navigation',
      description: 'Hamburger menu with animated slide-out drawer',
      tags: ['mobile', 'menu', 'hamburger', 'drawer', 'responsive'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'indicatorSize', 'showLabels'],
      defaultCustomization: {
        ...defaultCustomization,
        indicatorSize: '4',
        showLabels: 'true',
      },
    },
  ],
  effects: [
    {
      id: 'cursor-follow',
      name: 'Cursor Follow Effect',
      category: 'effects',
      description: 'Trailing cursor effect with blend modes',
      tags: ['cursor', 'trail', 'mouse', 'interactive'],
      customizableProps: ['glassOpacity', 'blurAmount', 'trailLength', 'cursorBlendMode', 'cursorSize'],
      defaultCustomization: {
        ...defaultCustomization,
        trailLength: '8',
        cursorBlendMode: 'screen',
        cursorSize: '20',
      },
    },
    {
      id: 'parallax-scroll',
      name: 'Parallax Scroll',
      category: 'effects',
      description: 'Multi-layer parallax scrolling effect',
      tags: ['parallax', 'scroll', 'layers', 'depth'],
      customizableProps: ['glassOpacity', 'blurAmount', 'parallaxSpeed', 'layerCount', 'parallaxDirection'],
      defaultCustomization: {
        ...defaultCustomization,
        parallaxSpeed: '0.5',
        layerCount: '3',
        parallaxDirection: 'vertical',
      },
    },
    {
      id: 'glow-button',
      name: 'Glow Button',
      category: 'effects',
      description: 'Buttons with animated glow, shimmer, and pulsing effects',
      tags: ['glow', 'button', 'shimmer', 'pulse', 'neon'],
      customizableProps: ['glassOpacity', 'blurAmount', 'glowIntensity', 'glowSpread', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        glowIntensity: '60',
        glowSpread: '40',
      },
    },
    {
      id: 'magnetic-element',
      name: 'Magnetic Element',
      category: 'effects',
      description: 'Elements that follow cursor with spring physics',
      tags: ['magnetic', 'cursor', 'interactive', 'physics', '3d'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
      },
    },
    {
      id: 'reveal-on-scroll',
      name: 'Reveal On Scroll',
      category: 'effects',
      description: 'Content that animates in as you scroll into view',
      tags: ['reveal', 'scroll', 'fade', 'animation', 'stagger'],
      customizableProps: ['glassOpacity', 'blurAmount', 'duration', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        duration: '600',
      },
    },
    {
      id: 'typewriter-text',
      name: 'Typewriter Text',
      category: 'effects',
      description: 'Text that types out letter by letter with cursor',
      tags: ['typewriter', 'text', 'animation', 'typing', 'terminal'],
      customizableProps: ['glassOpacity', 'blurAmount', 'duration', 'borderRadius'],
      defaultCustomization: {
        ...defaultCustomization,
        duration: '80',
      },
    },
  ],
  'data-display': [
    {
      id: 'stat-card',
      name: 'Stat Card',
      category: 'data-display',
      description: 'Animated statistics cards with trend indicators',
      tags: ['stats', 'metrics', 'dashboard', 'trends', 'analytics'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'iconSize', 'showTrend', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        iconSize: '24',
        showTrend: 'true',
        showGrid: 'false',
        dataPointSize: '8',
      },
    },
    {
      id: 'metric-tile',
      name: 'Metric Tile',
      category: 'data-display',
      description: 'System metrics display with progress bars and sparkline',
      tags: ['metrics', 'progress', 'sparkline', 'dashboard', 'monitoring'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'true',
        dataPointSize: '6',
      },
    },
    {
      id: 'progress-ring',
      name: 'Progress Ring',
      category: 'data-display',
      description: 'Animated concentric progress rings with SVG',
      tags: ['progress', 'ring', 'circular', 'svg', 'animated'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        showGrid: 'false',
        dataPointSize: '8',
      },
    },
    {
      id: 'area-chart',
      name: 'Area Chart',
      category: 'data-display',
      description: 'SVG area chart with gradient fill and animated line',
      tags: ['chart', 'area', 'svg', 'analytics', 'graph', 'data'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'true',
        dataPointSize: '6',
      },
    },
    {
      id: 'bar-chart',
      name: 'Bar Chart',
      category: 'data-display',
      description: 'Animated bar chart with comparison data and hover effects',
      tags: ['chart', 'bar', 'comparison', 'analytics', 'graph', 'data'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'true',
        dataPointSize: '8',
      },
    },
    {
      id: 'donut-chart',
      name: 'Donut Chart',
      category: 'data-display',
      description: 'Circular donut chart with center label and legend',
      tags: ['chart', 'donut', 'pie', 'circular', 'analytics', 'percentage'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'false',
        dataPointSize: '8',
      },
    },
    {
      id: 'sparkline-card',
      name: 'Sparkline Card',
      category: 'data-display',
      description: 'Mini chart in a card with trend indicator and value',
      tags: ['sparkline', 'mini-chart', 'trend', 'metrics', 'dashboard'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'false',
        dataPointSize: '4',
      },
    },
    {
      id: 'activity-feed',
      name: 'Activity Feed',
      category: 'data-display',
      description: 'List of recent activities with avatars and timestamps',
      tags: ['activity', 'feed', 'notifications', 'timeline', 'realtime'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'false',
        dataPointSize: '8',
      },
    },
    {
      id: 'data-table',
      name: 'Data Table',
      category: 'data-display',
      description: 'Styled table with sortable columns and row actions',
      tags: ['table', 'data', 'grid', 'sortable', 'pagination'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'true',
        dataPointSize: '8',
      },
    },
    {
      id: 'kpi-card',
      name: 'KPI Card',
      category: 'data-display',
      description: 'Key performance indicator with target and progress',
      tags: ['kpi', 'performance', 'target', 'progress', 'metrics'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'false',
        dataPointSize: '8',
      },
    },
    {
      id: 'counter-card',
      name: 'Counter Card',
      category: 'data-display',
      description: 'Animated number counter with live indicator',
      tags: ['counter', 'number', 'animated', 'live', 'realtime'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'false',
        dataPointSize: '8',
      },
    },
    {
      id: 'heatmap-cell',
      name: 'Heatmap Cell',
      category: 'data-display',
      description: 'Color-coded heatmap grid for data visualization',
      tags: ['heatmap', 'grid', 'color-coded', 'activity', 'calendar'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'true',
        dataPointSize: '12',
      },
    },
    {
      id: 'timeline-vertical',
      name: 'Timeline Vertical',
      category: 'data-display',
      description: 'Vertical timeline with nodes and status indicators',
      tags: ['timeline', 'vertical', 'progress', 'roadmap', 'milestones'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showGrid', 'dataPointSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showGrid: 'false',
        dataPointSize: '16',
      },
    },
  ],
  modals: [
    {
      id: 'glass-modal',
      name: 'Glass Modal',
      category: 'modals',
      description: 'Glassmorphic modal dialog with blur backdrop',
      tags: ['modal', 'glass', 'dialog', 'blur', 'overlay'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'backdropOpacity', 'modalScale'],
      defaultCustomization: {
        ...defaultCustomization,
        glassOpacity: '15',
        blurAmount: '12',
        backdropOpacity: '50',
        modalScale: '100',
      },
    },
    {
      id: 'slide-drawer',
      name: 'Slide Drawer',
      category: 'modals',
      description: 'Side drawer navigation with push effect',
      tags: ['drawer', 'slide', 'navigation', 'sidebar', 'menu'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'backdropOpacity', 'modalScale'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        backdropOpacity: '50',
        modalScale: '100',
      },
    },
    {
      id: 'confirm-dialog',
      name: 'Confirm Dialog',
      category: 'modals',
      description: 'Confirmation dialog with action buttons for destructive actions',
      tags: ['confirm', 'dialog', 'modal', 'delete', 'warning', 'alert'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'backdropOpacity', 'modalScale'],
      defaultCustomization: {
        ...defaultCustomization,
        backdropOpacity: '60',
        modalScale: '100',
      },
    },
    {
      id: 'image-lightbox',
      name: 'Image Lightbox',
      category: 'modals',
      description: 'Image preview overlay with zoom, navigation, and thumbnails',
      tags: ['lightbox', 'image', 'gallery', 'zoom', 'preview', 'overlay'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'backdropOpacity', 'modalScale'],
      defaultCustomization: {
        ...defaultCustomization,
        backdropOpacity: '80',
        modalScale: '100',
      },
    },
    {
      id: 'command-modal',
      name: 'Command Modal',
      category: 'modals',
      description: 'VS Code-style command palette modal with search and shortcuts',
      tags: ['command', 'palette', 'modal', 'search', 'keyboard', 'shortcuts'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'backdropOpacity', 'modalScale'],
      defaultCustomization: {
        ...defaultCustomization,
        backdropOpacity: '50',
        modalScale: '100',
      },
    },
    {
      id: 'bottom-sheet',
      name: 'Bottom Sheet',
      category: 'modals',
      description: 'Mobile-style bottom sheet with drag-to-dismiss gesture',
      tags: ['bottom-sheet', 'mobile', 'drawer', 'share', 'actions', 'swipe'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'backdropOpacity', 'modalScale'],
      defaultCustomization: {
        ...defaultCustomization,
        backdropOpacity: '50',
        modalScale: '100',
      },
    },
  ],
  feedback: [
    {
      id: 'toast-notification',
      name: 'Toast Notification',
      category: 'feedback',
      description: 'Toast popup notifications with success, error, warning, and info variants',
      tags: ['toast', 'notification', 'alert', 'success', 'error', 'popup'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'toastWidth', 'showIcon', 'animationSpeed'],
      defaultCustomization: {
        ...defaultCustomization,
        toastWidth: '320',
        showIcon: 'true',
        animationSpeed: '300',
      },
    },
    {
      id: 'alert-banner',
      name: 'Alert Banner',
      category: 'feedback',
      description: 'Full-width alert banner with dismiss and action buttons',
      tags: ['alert', 'banner', 'notification', 'warning', 'info', 'dismissible'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'showIcon', 'animationSpeed'],
      defaultCustomization: {
        ...defaultCustomization,
        showIcon: 'true',
        animationSpeed: '300',
      },
    },
    {
      id: 'progress-loader',
      name: 'Progress Loader',
      category: 'feedback',
      description: 'Full-screen loading overlay with animated spinner and progress bar',
      tags: ['loading', 'spinner', 'progress', 'overlay', 'async', 'wait'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'showIcon', 'animationSpeed'],
      defaultCustomization: {
        ...defaultCustomization,
        showIcon: 'true',
        animationSpeed: '1000',
      },
    },
    {
      id: 'success-state',
      name: 'Success State',
      category: 'feedback',
      description: 'Success confirmation with animated checkmark and confetti effect',
      tags: ['success', 'checkmark', 'confetti', 'complete', 'celebration', 'done'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'showIcon', 'animationSpeed'],
      defaultCustomization: {
        ...defaultCustomization,
        showIcon: 'true',
        animationSpeed: '500',
      },
    },
  ],
  headers: [
    {
      id: 'sticky-header',
      name: 'Sticky Header',
      category: 'headers',
      description: 'Header that shrinks and adds blur effect on scroll',
      tags: ['header', 'sticky', 'scroll', 'shrink', 'blur', 'navigation'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'headerHeight', 'showDivider'],
      defaultCustomization: {
        ...defaultCustomization,
        glassOpacity: '15',
        blurAmount: '12',
        headerHeight: '64',
        showDivider: 'true',
      },
    },
    {
      id: 'centered-header',
      name: 'Centered Header',
      category: 'headers',
      description: 'Elegant header with logo centered and navigation on sides',
      tags: ['header', 'centered', 'logo', 'elegant', 'boutique', 'luxury'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'headerHeight', 'showDivider'],
      defaultCustomization: {
        ...defaultCustomization,
        headerHeight: '72',
        showDivider: 'true',
      },
    },
    {
      id: 'transparent-header',
      name: 'Transparent Header',
      category: 'headers',
      description: 'Glassmorphic transparent header with blur backdrop',
      tags: ['header', 'transparent', 'glass', 'blur', 'modern', 'landing'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'headerHeight', 'showDivider'],
      defaultCustomization: {
        ...defaultCustomization,
        glassOpacity: '15',
        blurAmount: '12',
        headerHeight: '64',
        showDivider: 'false',
      },
    },
    {
      id: 'mega-menu-header',
      name: 'Mega Menu Header',
      category: 'headers',
      description: 'Header with feature-rich dropdown mega menu panels',
      tags: ['header', 'mega-menu', 'dropdown', 'navigation', 'enterprise'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'headerHeight', 'showDivider'],
      defaultCustomization: {
        ...defaultCustomization,
        headerHeight: '72',
        showDivider: 'true',
      },
    },
  ],
  footers: [
    {
      id: 'multi-column-footer',
      name: 'Multi-Column Footer',
      category: 'footers',
      description: 'Comprehensive footer with multiple link columns and newsletter',
      tags: ['footer', 'columns', 'links', 'newsletter', 'contact'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'columnCount', 'showSocialLinks'],
      defaultCustomization: {
        ...defaultCustomization,
        columnCount: '4',
        showSocialLinks: 'true',
      },
    },
    {
      id: 'minimal-footer',
      name: 'Minimal Footer',
      category: 'footers',
      description: 'Clean centered footer with essential links only',
      tags: ['footer', 'minimal', 'simple', 'centered', 'clean'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'columnCount', 'showSocialLinks'],
      defaultCustomization: {
        ...defaultCustomization,
        columnCount: '1',
        showSocialLinks: 'true',
      },
    },
    {
      id: 'cta-footer',
      name: 'CTA Footer',
      category: 'footers',
      description: 'Footer with prominent newsletter signup call-to-action',
      tags: ['footer', 'cta', 'newsletter', 'signup', 'email', 'subscribe'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'columnCount', 'showSocialLinks'],
      defaultCustomization: {
        ...defaultCustomization,
        columnCount: '3',
        showSocialLinks: 'true',
      },
    },
    {
      id: 'social-footer',
      name: 'Social Footer',
      category: 'footers',
      description: 'Footer focused on social media links with follower counts',
      tags: ['footer', 'social', 'twitter', 'github', 'linkedin', 'instagram'],
      customizableProps: ['glassOpacity', 'blurAmount', 'borderRadius', 'columnCount', 'showSocialLinks'],
      defaultCustomization: {
        ...defaultCustomization,
        columnCount: '1',
        showSocialLinks: 'true',
      },
    },
  ],
  heroes: [
    {
      id: 'gradient-hero',
      name: 'Gradient Hero',
      category: 'heroes',
      description: 'Hero section with animated gradient orbs and CTA buttons',
      tags: ['hero', 'gradient', 'landing', 'cta', 'animated'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'borderRadius', 'heroHeight', 'showBadge'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        heroHeight: '600',
        showBadge: 'true',
      },
      textSlots: [
        { key: 'badge', label: 'Badge', defaultValue: 'New Release' },
        { key: 'headline', label: 'Headline', defaultValue: 'Build Beautiful Interfaces' },
        { key: 'subheadline', label: 'Subheadline', defaultValue: 'Create stunning, modern UI components with our powerful design system.', multiline: true },
        { key: 'primaryCta', label: 'Primary CTA', defaultValue: 'Get Started' },
        { key: 'secondaryCta', label: 'Secondary CTA', defaultValue: 'Learn More' },
      ],
    },
    {
      id: 'bento-hero',
      name: 'Bento Hero',
      category: 'heroes',
      description: 'Bento grid layout hero with feature cards',
      tags: ['bento', 'grid', 'hero', 'features', 'layout'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'heroHeight', 'showBadge'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        heroHeight: '700',
        showBadge: 'true',
      },
    },
    {
      id: 'terminal-hero',
      name: 'Terminal Hero',
      category: 'heroes',
      description: 'Developer-focused hero with terminal window and code aesthetic',
      tags: ['hero', 'terminal', 'developer', 'code', 'cli', 'landing'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'borderRadius', 'heroHeight', 'showBadge'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        heroHeight: '600',
        showBadge: 'true',
      },
    },
    {
      id: 'video-hero',
      name: 'Video Hero',
      category: 'heroes',
      description: 'Hero section with video player placeholder and overlay controls',
      tags: ['hero', 'video', 'media', 'landing', 'demo', 'play'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'borderRadius', 'heroHeight', 'showBadge'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        heroHeight: '650',
        showBadge: 'false',
      },
    },
  ],
  pricing: [
    {
      id: 'pricing-card',
      name: 'Pricing Card',
      category: 'pricing',
      description: 'Featured pricing card with shimmer effect and feature list',
      tags: ['pricing', 'card', 'features', 'cta', 'shimmer'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showPopular', 'columnCount'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        glassOpacity: '15',
        showPopular: 'true',
        columnCount: '3',
      },
      textSlots: [
        { key: 'planName', label: 'Plan Name', defaultValue: 'Pro' },
        { key: 'price', label: 'Price', defaultValue: '$29' },
        { key: 'period', label: 'Period', defaultValue: '/month' },
        { key: 'description', label: 'Description', defaultValue: 'Perfect for growing teams', multiline: true },
        { key: 'buttonText', label: 'Button Text', defaultValue: 'Get Started' },
      ],
    },
    {
      id: 'feature-grid',
      name: 'Feature Grid',
      category: 'pricing',
      description: 'Hover-activated feature grid with icons and descriptions',
      tags: ['features', 'grid', 'icons', 'hover', 'marketing'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showPopular', 'columnCount'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showPopular: 'false',
        columnCount: '3',
      },
    },
  ],
  testimonials: [
    {
      id: 'testimonial-card',
      name: 'Testimonial Card',
      category: 'testimonials',
      description: 'Customer testimonial with rating, quote, and avatar',
      tags: ['testimonial', 'review', 'rating', 'quote', 'social-proof'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showAvatar', 'quoteSize'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        glassOpacity: '15',
        showAvatar: 'true',
        quoteSize: '18',
      },
    },
    {
      id: 'quote-card',
      name: 'Quote Card',
      category: 'testimonials',
      description: 'Inspirational quote card with animated gradient border',
      tags: ['quote', 'gradient', 'border', 'inspiration', 'animated'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'borderRadius', 'showAvatar', 'quoteSize'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        showAvatar: 'false',
        quoteSize: '24',
      },
    },
  ],
  auth: [
    {
      id: 'login-card',
      name: 'Login Card',
      category: 'auth',
      description: 'Complete login form with social auth and animations',
      tags: ['login', 'auth', 'form', 'social', 'password'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showSocialLogin', 'formWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        glassOpacity: '15',
        showSocialLogin: 'true',
        formWidth: '400',
      },
    },
    {
      id: 'signup-card',
      name: 'Signup Card',
      category: 'auth',
      description: 'Registration form with password strength indicator',
      tags: ['signup', 'register', 'auth', 'form', 'password-strength'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'showSocialLogin', 'formWidth'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        showSocialLogin: 'true',
        formWidth: '400',
      },
    },
  ],
  marketing: [
    {
      id: 'cta-section',
      name: 'CTA Section',
      category: 'marketing',
      description: 'Call-to-action section with headline, subtext, and buttons',
      tags: ['cta', 'call-to-action', 'marketing', 'conversion', 'landing'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'shadowIntensity', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        shadowIntensity: '50',
        sectionPadding: '80',
        showDecorations: 'true',
      },
      textSlots: [
        { key: 'headline', label: 'Headline', defaultValue: 'Ready to Get Started?' },
        { key: 'subtext', label: 'Subtext', defaultValue: 'Join thousands of developers building amazing products.', multiline: true },
        { key: 'primaryCta', label: 'Primary CTA', defaultValue: 'Start Free Trial' },
        { key: 'secondaryCta', label: 'Secondary CTA', defaultValue: 'Schedule Demo' },
      ],
    },
    {
      id: 'feature-showcase',
      name: 'Feature Showcase',
      category: 'marketing',
      description: 'Single feature highlight with image and benefits list',
      tags: ['feature', 'showcase', 'marketing', 'benefits', 'product'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'shadowIntensity', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        shadowIntensity: '50',
        sectionPadding: '80',
        showDecorations: 'true',
      },
    },
    {
      id: 'logo-cloud',
      name: 'Logo Cloud',
      category: 'marketing',
      description: 'Grid of partner/client logos with hover effects',
      tags: ['logos', 'partners', 'clients', 'trust', 'brands'],
      customizableProps: ['glassOpacity', 'blurAmount', 'shadowIntensity', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        shadowIntensity: '50',
        sectionPadding: '60',
        showDecorations: 'false',
      },
    },
    {
      id: 'trust-badges',
      name: 'Trust Badges',
      category: 'marketing',
      description: 'Security and compliance badges row with animations',
      tags: ['trust', 'security', 'badges', 'compliance', 'certification'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        sectionPadding: '40',
        showDecorations: 'false',
      },
    },
    {
      id: 'stats-counter',
      name: 'Stats Counter',
      category: 'marketing',
      description: 'Animated statistics row with counters and trends',
      tags: ['stats', 'counter', 'metrics', 'numbers', 'animated'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'shadowIntensity', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        shadowIntensity: '50',
        sectionPadding: '60',
        showDecorations: 'true',
      },
    },
    {
      id: 'comparison-table',
      name: 'Comparison Table',
      category: 'marketing',
      description: 'Feature comparison table with checkmarks and plans',
      tags: ['comparison', 'table', 'features', 'plans', 'pricing'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        sectionPadding: '80',
        showDecorations: 'false',
      },
    },
    {
      id: 'faq-accordion',
      name: 'FAQ Accordion',
      category: 'marketing',
      description: 'Expandable FAQ section with smooth animations',
      tags: ['faq', 'accordion', 'questions', 'answers', 'support'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        sectionPadding: '60',
        showDecorations: 'false',
      },
    },
    {
      id: 'newsletter-signup',
      name: 'Newsletter Signup',
      category: 'marketing',
      description: 'Email capture form with input and submit button',
      tags: ['newsletter', 'email', 'signup', 'subscribe', 'capture'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'shadowIntensity', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        shadowIntensity: '50',
        sectionPadding: '60',
        showDecorations: 'true',
      },
    },
    {
      id: 'announcement-banner',
      name: 'Announcement Banner',
      category: 'marketing',
      description: 'Top banner with dismissible announcement message',
      tags: ['announcement', 'banner', 'alert', 'notification', 'promo'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        sectionPadding: '16',
        showDecorations: 'true',
      },
    },
    {
      id: 'social-proof',
      name: 'Social Proof',
      category: 'marketing',
      description: 'Avatar stack with user count and rating display',
      tags: ['social-proof', 'avatars', 'users', 'rating', 'reviews'],
      customizableProps: ['glassOpacity', 'blurAmount', 'gradientAngle', 'shadowIntensity', 'borderRadius', 'sectionPadding', 'showDecorations'],
      defaultCustomization: {
        ...defaultCustomization,
        gradientAngle: '135',
        shadowIntensity: '50',
        sectionPadding: '40',
        showDecorations: 'false',
      },
    },
  ],
};

// Get all components as flat array
export function getAllComponents(): ComponentDefinition[] {
  return Object.values(componentLibrary).flat();
}

// Get component by ID
export function getComponentById(id: string): ComponentDefinition | undefined {
  return getAllComponents().find((c) => c.id === id);
}

// Get components by category
export function getComponentsByCategory(category: ComponentCategory): ComponentDefinition[] {
  return componentLibrary[category] || [];
}

// Get categories with component counts
export function getCategoriesWithCounts(): { category: ComponentCategory; count: number }[] {
  return Object.entries(componentLibrary).map(([category, components]) => ({
    category: category as ComponentCategory,
    count: components.length,
  }));
}

// Search components by query
export function searchComponents(query: string): ComponentDefinition[] {
  const lowerQuery = query.toLowerCase();
  return getAllComponents().filter(
    (c) =>
      c.name.toLowerCase().includes(lowerQuery) ||
      c.description.toLowerCase().includes(lowerQuery) ||
      c.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}

// Category display names
export const categoryDisplayNames: Record<ComponentCategory, string> = {
  cards: 'Cards',
  buttons: 'Buttons',
  badges: 'Badges',
  forms: 'Forms',
  navigation: 'Navigation',
  effects: 'Effects',
  'data-display': 'Data Display',
  modals: 'Modals & Overlays',
  feedback: 'Feedback & Alerts',
  headers: 'Headers',
  footers: 'Footers',
  heroes: 'Heroes & Landing',
  pricing: 'Pricing & Features',
  testimonials: 'Testimonials',
  auth: 'Authentication',
  marketing: 'Marketing & Landing',
};

// Category icons (lucide icon names)
export const categoryIcons: Record<ComponentCategory, string> = {
  cards: 'CreditCard',
  buttons: 'MousePointer',
  badges: 'Badge',
  forms: 'FileText',
  navigation: 'Menu',
  effects: 'Sparkles',
  'data-display': 'BarChart3',
  modals: 'Layers',
  feedback: 'Bell',
  headers: 'PanelTop',
  footers: 'PanelBottom',
  heroes: 'Layout',
  pricing: 'DollarSign',
  testimonials: 'Quote',
  auth: 'Lock',
  marketing: 'Megaphone',
};
